### ISSUE TITLE
const exports = {} fails on bundling with webpack and esbuild

### ISSUE THREAD

**Issue by geodatenanwendungenhamburg** [openlayers/ol-cesium#1006]
We changed the bundling with webpack and replaced babel-loader with esbuild-loader.
This raises in an error in olcs:

> stderr: 'Error: Transform failed with 2 errors:\n' +
    'js/masterportal.js:30161:6: ERROR: The symbol "exports" has already been declared\n' +
    'js/masterportal.js:45327:6: ERROR: The symbol "exports" has already been declared\n' +
    '    at failureErrorWithLog (C:\\foo\\baa\\masterportal\\node_modules\\esbuild\\lib\\main.js:1566:15)\n' +
    '    at C:\\foo\\baa\\masterportal\\node_modules\\esbuild\\lib\\main.js:805:29\n' +
    '    at responseCallbacks.<computed> (C:\\foo\\baa\\masterportal\\node_modules\\esbuild\\lib\\main.js:671:9)\n' +
    '    at handleIncomingPacket (C:\\foo\\baa\\masterportal\\node_modules\\esbuild\\lib\\main.js:726:9)\n' +
    '    at Socket.readFromStdout (C:\\foo\\baa\\masterportal\\node_modules\\esbuild\\lib\\main.js:647:7)\n' +
    '    at Socket.emit (node:events:527:28)\n' +
    '    at addChunk (node:internal/streams/readable:315:12)\n' +
    '    at readableAddChunk (node:internal/streams/readable:289:9)\n' +
    '    at Socket.Readable.push (node:internal/streams/readable:228:10)\n' +
    '    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)\n'

The reason is:

`const exports = {};`

in olcs/util.js and in olcs/core.js

Can you rename the variable exports?

At the moment we are renaming the originating code during the build process.

**Comment by gberaudo** [comment]
Hi @geodatenanwendungenhamburg. Indeed these `exports` variables are the remaining of pre-ES6 module system.
These should all be removed from the code (we should use standard named exports).

Would you want to contribute a PR to fix that?

**Comment by eblondel** [comment]
@gberaudo I suppose #1012 is the same issue (on Parcel). I might have to time to contribute to a PR, but i'd need more guidance. Do you expect to create classes for core and utils? as for the other js files here. 
Thanks in advance

**Comment by gberaudo** [comment]
I @eblondel , thanks for proposing your help.
You simply need to create named exports/imports. Like following example:

```js
/**
 * @module olcs.util
 */
const exports = {};


/**
 * Cast to object.
 * @param {Object} param
 * @return {Object}
 */
exports.obj = function(param) {
  return param;
};
```
-> becomes:
```js
/**
 * Cast to object.
 * @param {Object} param
 * @return {Object}
 */
export function obj(param) {
  return param;
}
```

And to use it:
```js
import {obj} from '..../util.js';
```

**Comment by gberaudo** [comment]
Hi, this has been fixed in the latest release.
