### ISSUE TITLE
When switching from ol to cesium, thousands of warnings appear, and cesium displays slowly

### ISSUE THREAD

**Issue by 279zlj** [openlayers/ol-cesium#1007]
The following warning appears when switching from ol to cesium：
Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true.
Up to thousands
Text dot, line and face exist in ol before switching

**Comment by jahow** [comment]
Most likely related to https://github.com/openlayers/openlayers/issues/14175

Maybe updating OL would help?
