### ISSUE TITLE
Using Photorealistic 3D Tiles in OLCesium

### ISSUE THREAD

**Issue by jmgomezpoveda** [openlayers/ol-cesium#1056]
I have seen the new Photorealistic 3D Tiles in Cesium. However, I am unable to follow [the Cesium guide](https://cesium.com/learn/cesiumjs-learn/cesiumjs-photorealistic-3d-tiles/).

My code is:

```
var map3d = new OLCesium({map: this.jmap.map});
var scene = map3d.getCesiumScene();
scene.globe = false;
Cesium.GoogleMaps.defaultApiKey = config.env.GOOGLEKEY;
try {
    const tileset = Cesium.createGooglePhotorealistic3DTileset().then((value) => {
        scene.primitives.add(tileset);
    });
} catch (error) {
    console.log(`Failed to load tileset: ${error}`);
}
```

With this code I am getting a blank display and an error "Uncaught TypeError: t.imageryLayersUpdatedEvent is undefined". This happens when I do that initial "scene.globe = false".

If I skip that "scene.globe = false", there is no error, but the screen stays black.

Am I doing anything wrong? What is the way to enable photorealistic 3D tiles with OLCesium?

  [1]: https://cesium.com/learn/cesiumjs-learn/cesiumjs-photorealistic-3d-tiles/

**Comment by gberaudo** [comment]
Hi @jmgomezpoveda,
Have you tried that code with plain Cesium first?

Are you sure the problem is in OL-Cesium?
If you did try with plain Cesium and you think the issue is in OL-Cesium itself, then please re-open.

**Comment by groundrace** [comment]
to get this fixed is enough to use the exposed Cesium from ol-cesium that is the one referenced with the ```window.Cesium```

```
// @ts-ignore
const tileset = **window.**Cesium.createGooglePhotorealistic3DTileset().then((value) => {
```

if you use typescript you may need to add the @ts-ignore directive just a line before
