### ISSUE TITLE
Pinch Interactions not working properly in 3D

### ISSUE THREAD

**Issue by geodatenanwendungenhamburg** [openlayers/ol-cesium#1065]
Hey everybody,

we noticed that pinch interactions to rotate or to zoom are not working properly on the recent android/chrome versions in 3D (safari as well). If you open https://openlayers.org/ol-cesium/examples/overlay.html for example, Rotating via pinch in cesium is being aborted after minimal rotating while interactions on the ol-side are working. We're not getting these effects with 'naked' cesiumapp like for example in https://cesium.com/learn/cesiumjs-learn/cesiumjs-quickstart/. So we assumed that this may relate to ol-cesium. Also to be seen in https://www.geoportal-hamburg.de/geo-online/?map=3d.

best regards
Markus

**Comment by ismailsunni** [comment]
It seems it's similar to this issue #981 

and yes, I got the same issues.

**Comment by gberaudo** [comment]
Hi @geodatenanwendungenhamburg, thanks for your precise feedback.

I can indeed reproduce it with chrome on android.
Firefox works correctly.

I agree with you @ismailsunni.

**Comment by gberaudo** [comment]
Hi @geodatenanwendungenhamburg, the problem is linked to https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action#none

@ismailsunni is working on a fix.

**Comment by geodatenanwendungenhamburg** [comment]
Oh, thanks for the investigation!

"@ismailsunni is working on a fix." - sounds great :-)
