### ISSUE TITLE
TypeScript files referenced in JavaScript release causing module resolution error

### ISSUE THREAD

**Issue by 22-David** [openlayers/ol-cesium#1088]
The current release (2.15.1) does only include JavaScript files, but there are TypeScript files still being referenced within the JavaScript code, which is causing module resolution errors during webpack bundling.

Example:
ERROR in ./node_modules/olcs/FeatureConverter.js
Module not found: Error: Can't resolve './core.ts' in 'path/to/project/node_modules/olcs'

Here is a list of all TypeScript references causing the errors:
- Camera.js references './core.ts'
- OLImageryProvider.js references './core.ts'
- FeatureConverter.js references './core/VectorLayerCounterpart.ts' 
- FeatureConverter.js references './core.ts'

**Comment by gberaudo** [comment]
Hi @22-David, thanks for the report, I will look into it.

**Comment by gberaudo** [comment]
Hi @22-David , I published a new release. Let me know if it fixes your issue.

**Comment by foo4foo** [comment]
@gberaudo I'm having the same problem with latest `olcs` and `ol-cesium` packages. I tried both in combination with `cesium`.

**Comment by 22-David** [comment]
> Hi @22-David , I published a new release. Let me know if it fixes your issue.

Thank you very much for the quick solution. It´s working fine now (version 2.15.2).
