### ISSUE TITLE
Examples from README are not working

### ISSUE THREAD

**Issue by foo4foo** [openlayers/ol-cesium#1095]
I couldn't make `cesium` work with latest `openlayers` nor version 6.x. Examples from the `README` are misleading and many errors are showing up. I think the errors are not important at the moment because there are so many issues here where people report all kinds of problems.

Can we have a working step by step example with `webpack` >= v4, please ? I think a lot of people are having a hard time following the `README`.

It would be good to have this example with `cesium` installed rather than using it as a script in .html file. If not, adding it add as a script tag is fine.

**Comment by gberaudo** [comment]
Hi @foo4foo, thanks for your feedback.

I agree with you, the README needs a clean up.
What did you do?

**Comment by gberaudo** [comment]
The README was reworked.
Also there is some ongoing work on improving examples like adding a click button to live edit them.
