### ISSUE TITLE
Npm version 2.16.1

### ISSUE THREAD

**Issue by lmarcelocc** [openlayers/ol-cesium#1142]
Hello,

Is it possible for you guys to make available, perhaps version 2.16.1, with [this](https://github.com/openlayers/ol-cesium/commit/b2f0c0550620644c02ade650cb2e8e6887437591) fix ?

Thank you and happy new year :tada:

**Comment by gberaudo** [comment]
Hi @lmarcelocc, I am finalizing v2.17 which should be available circa start of next week.
My goal is to concentrate the effort on this 2.17 but if it takes too much time I will release a v2.16.x.

**Comment by lmarcelocc** [comment]
Thanks @gberaudo  ;)

**Comment by gberaudo** [comment]
Hi @lmarcelocc, I just published v2.17 so I am closing your issue.
