### ISSUE TITLE
Jagged edges on shadows

### ISSUE THREAD

**Issue by mulfvik** [openlayers/ol-cesium#1201]
The solution could be to [increase resolution](https://community.cesium.com/t/strange-behaviour-of-shadows-on-3d-tiles/7601) in the viewers shadow map. I am keen to help with this issue but could need some guidance how to get hold of the shadow map method
![image](https://github.com/openlayers/ol-cesium/assets/24228538/b166f3a4-6e5e-4c21-a76c-9c3143d26085)

**Comment by gberaudo** [comment]
Hi @mulfvik , you can directly access the `shadowMap` with `ol3d.getCesiumScene().shadowMap`;
