### ISSUE TITLE
Additional map projections (SRS) for raster formats

### ISSUE THREAD

**Issue by gberaudo** [openlayers/ol-cesium#37]
Cesium supports several raster formats, notably:
- WMTS;
- WMS.

In ol3cesium, we are currently restricted to a custom ol3 tile image provider.
This imagery provider gets the tiles from an ol.source.TileImage in either 4326 or 
3857 projection.

Other or different projections in ol3 and Cesium are not possible.
WMS or WMTS are not handled.

**Comment by gberaudo** [comment]
Client side reprojection has been added to OpenLayers.
A nice improvement would be to have OL-Cesium make use of it.

**Comment by klokan** [comment]
@klokantech team has implemented the client side reprojection in OpenLayers.

We can implement a compatibility layer into OL-Cesium, if there is a client willing to cover the working hours of related effort. Just let us know.

**Comment by gberaudo** [comment]
Great, thanks for the information.

**Comment by pksorensen** [comment]
@klokan Any estimate of work effort needed to do this? 

Am i wrong to think it could be rather easy as the reprojection to 3857 can already be done with the ol3 implementation you guys did - and its just a matter of exposing those tiles as dataurls to cesium tile layer?

Atleast if we know what kind of effort is needed it might be easier to raise the money.

**Comment by klokan** [comment]
@pksorensen please contact info@klokantech.com

**Comment by samuel-girard** [comment]
Hello,
I am also interested in client side reprojection of tiles (to manage more projections than just 3857 and 4326) in Cesium/ol-cesium.
Has there been any progress on this?

**Comment by gberaudo** [comment]
@samuel-girard, @pksorensen, I experimented with it a long time ago in https://github.com/gberaudo/ol3-cesium/tree/wip_client_raster_reprojection.

From my memories it was working in most cases but the rastersync example had 1 case broken. I will try to find some time for refresing the branch. If someone wants to have a look, help is always welcomed.

**Comment by gberaudo** [comment]
@pksorensen, @samuel-girard, could you please test #562?

**Comment by samuel-girard** [comment]
Hi @gberaudo 

Thank you for that!
I just tried #562 and it does not seem to work:
On the customProj example, I get a black globe:
![image](https://user-images.githubusercontent.com/32910196/36942859-ca1ba8d6-1f7d-11e8-9231-053b283b53fc.png)
With the imageWMS example, only half of OSM layer is loaded (longitude from 0 to 180):
![image](https://user-images.githubusercontent.com/32910196/36942873-11309858-1f7e-11e8-8220-4ba94907c9f2.png)

None of them show error in the console.
I'll give it a deeper look next week.

**Comment by samuel-girard** [comment]
Hello @gberaudo 

I just tried the branch and it works! I don't know what I did wrong last time to have such result...
So far, I have found only one little glitch in the example you give. Some kind of shadow appears under the tile:
![image](https://user-images.githubusercontent.com/32910196/37105480-9081ab0c-222f-11e8-843a-4745975e3060.png)
and it stays there when I zoom in:
![image](https://user-images.githubusercontent.com/32910196/37105522-ad7f31ac-222f-11e8-8177-18d849245cc9.png)

I will try to integrate this modification in our project soon, so I can test more cases and will let you know if I meet any issues.

**Comment by gberaudo** [comment]
Thanks for the feedback @samuel-girard. Yes, this shadow looks strange and it would be welcome if you are able to investigate further.

**Comment by wallw-bits** [comment]
@gberaudo I was also able to reproduce the odd screenshot above:

![screen shot 2018-04-12 at 6 10 48 pm](https://user-images.githubusercontent.com/7914731/38710323-069fe754-3e7d-11e8-9b13-c0294f8051cc.png)

It only occurs for me in Firefox (Chrome and Safari were fine) in EPSG:3857. EPSG:4326 works well in all of them. It's as if it was skipping columns, as the blank areas double as you zoom in.
