### ISSUE TITLE
Polylines on terrain

### ISSUE THREAD

**Issue by lucasvw** [openlayers/ol-cesium#375]
Hi guys,

Currently Cesium does not support polyline geometry as groundPrimitive. There are some people in the cesium groups forum who use the Corridor geometry as proxy. 

I wanted to ask if you have experience with this and if you are considering to also implement this in the ol3-cesium FeatureConverter?

Best,
Lucas

**Comment by gberaudo** [comment]
There has been no work or plan to implement this in OL3-Cesium. Would be cool though.
Do you have pointers to the forum threads?

**Comment by lucasvw** [comment]
https://groups.google.com/forum/#!searchin/cesium-dev/corridor$20as$20polyline/cesium-dev/JlR4KgkndlI/F7pQwjZpGwAJ

https://groups.google.com/forum/#!searchin/cesium-dev/corridor$20as$20polyline/cesium-dev/p2QNC2bvyiE/qxVM48HtCwAJ

And besides:

From here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md

> GeoJsonDataSource: Points with a height will be drawn at that height; otherwise, they will be clamped to the ground. Added clampToGround property. When true, clamps Polygon and LineString features to the ground. For this case, lines use a corridor instead of a polyline.

Perhaps one could look at that code for ideas..

**Comment by PurpleAlien** [comment]
So basically, it should be possible to just change the PolylineGeometry to a CorridorGeometry in the featureconverter (with appropriate clampToGround property)?

**Comment by gberaudo** [comment]
The corridor geometry has its width defined in meters. So I guess there needs to be some logics for updating the width according to distance.

**Comment by PurpleAlien** [comment]
I'd still be ok with that limitation for my application. However I just tried it and while it does work in principle, as soon as the amount of positions gets too large it stops drawing. For example, a polyline that comes back from an OSRM route calculation ends up having too many positions.

**Comment by PurpleAlien** [comment]
Actually, scratch that, it's not because of too many coordinates. Sometimes the CorridorGeometry object has its _rectangle properties (north, south, west,east) set to NaN - which I'm guessing is the reason it doesn't get drawn. No idea why this happens yet...

**Comment by gberaudo** [comment]
For some time already we are now using the Corridor geometry by default. It has drawbacks though (not adapting with distance and some artifacts, at least on my machine). We are still looking forward for a proper solution in Cesium.
