### ISSUE TITLE
GWT wrapper for ol3 and ol3-cesium(based on cesium-gwt)

### ISSUE THREAD

**Issue by iSergio** [openlayers/ol-cesium#384]
Maybe it will be interesting for community. Sorry if no.
This wrapper will strive for 100% implementation of the functional OpenLayers 3 and OL3-Cesium.
https://github.com/iSergio/gwt-olcs

**Comment by gberaudo** [comment]
Hi @iSergio, it looks great, thanks for sharing the link.
Can you explain in a few words how it works for people not used to GWT?
