### ISSUE TITLE
Does ol3-cesium breaks openlayers mobile functions?

### ISSUE THREAD

**Issue by am2222** [openlayers/ol-cesium#404]
Hi,
Sorry for my question but here I am confused, I want to use openlayers mobile features and they work great, then I want to add some 3d buildings on my map,Here I should use this library,So I want to know If I use this library does other open layers functions break?
I have to convert my layers data into cesiums format?In fact I have no idea how this library works.Can you please help me about this problem?

**Comment by gberaudo** [comment]
Sorry I missed your question.
> does other open layers functions break
no

> I have to convert my layers data into cesiums format?
Yes you have to convert your raster layers to a projection supported by Cesium.
For OpenLayers, you may either use the same data as Cesium or your data in any other projection.

I agree it would be great to have more documentation and examples. But I am short on time and cannot afford spending too much time on this. Any help from the community would be greatly welcomed.
