### ISSUE TITLE
vector style synch

### ISSUE THREAD

**Issue by lucasvw** [openlayers/ol-cesium#415]
Hi,

I noticed that changing the style on an openlayers vector layer didnt update the style of the associated primitives in cesium. My ol.Features dont have their own style, so the used style is the one from the layer. But when this is changed, the "changefeature" listener is not activated because the feature did not change.. 

As a workaround I now call the "changed" method on each feature after I update the style of such a layer but this is ofcourse not so ideal.

Could you imagine also listening to layer styleChanged events and updating the features?

**Comment by gberaudo** [comment]
It should already be the case. Do you have a snippet showing how you change the style?
