### ISSUE TITLE
How do show 3D models?

### ISSUE THREAD

**Issue by malvandi** [openlayers/ol-cesium#419]
I'm new in ol3-cesium. I want to show 3D models in 3D view and ol3 styles in 2D view. How can I do it?

**Comment by gberaudo** [comment]
That needs some work. You need to:
- extend olcs.FeatureConverter to return a Cesium primitive for each model;
- instanciate an olcs.VectorSynchronizer, passing in the converter;
- configure OLCesium to use your vector synchronizer (see the createSynchronizers option).
