### ISSUE TITLE
White globe when using projection EPSG:4326

### ISSUE THREAD

**Issue by jmgomezpoveda** [openlayers/ol-cesium#429]
When using projection EPSG:4326 in my OL3 Map, everything renders fine in 2D. However, once I switch to 3D, the globe appears white.

```
new ol.Map({
  /* ... */
  view: new ol.View({
    /* ... */
    projection: 'EPSG:4326'
  })
})
```

**Comment by gberaudo** [comment]
Strange, have you checked the epsg-4326 example?

**Comment by jmgomezpoveda** [comment]
Strange indeed, [that example](http://openlayers.org/ol3-cesium/examples/epsg-4326.html) seems to work fine. Will double check on my end.

**Comment by jmgomezpoveda** [comment]
Ok, I just made a couple of tests.

The EPSG:4326 example uses the following layer, which does work fine:

```
var layer = new ol.layer.Tile({
  source: new ol.source.TileWMS({
    url: 'http://demo.boundlessgeo.com/geoserver/wms',
    params: {
      'LAYERS': 'ne:NE1_HR_LC_SR_W_DR'
    }
  })
});
```

However, none of the following layers work:

```
var layer = new ol.layer.Tile({
    source: new ol.source.XYZ({
        url: 'https://api.tiles.mapbox.com/v4/mapbox.streets/{z}/{x}/{y}' + hidpiString + '.png?access_token='+my_key,
        tilePixelRatio: (isHiDPI() ? 2 : 1)
    })
});
```

```
var layer = new ol.layer.Tile({
    source: new ol.source.OSM({url: "//{a-c}.tile.thunderforest.com/landscape/{z}/{x}/{y}.png"})
});
```

```
var layer = new ol.layer.Tile({
    source: new ol.source.OSM()
});
```

```
var layer = new ol.layer.Tile({
    source: new ol.source.BingMaps({key: my_key, imagerySet: ['AerialWithLabels']})
});
```

**Comment by gberaudo** [comment]
Are you sure OSM and BingMaps are using EPSG:4326?

**Comment by jmgomezpoveda** [comment]
Well, any inputs should be visible regardless of the projection selected in the 2D view. Note that the projection is a property of the view, which should not affect to the 3D view altogether.

A (2D) sample of OSM using EPSG:4326 projection: https://jsfiddle.net/adlerhn/xt5m1o6d/7/

**Comment by gberaudo** [comment]
Your example makes use of OL3 raster reprojection, doesn't it?

**Comment by jmgomezpoveda** [comment]
I was not familiar with this raster reprojection, but after looking it up, yes, that is what must be happening under the hood.

**Comment by gberaudo** [comment]
Currently there is no support for this in OL3-Cesium. So it is normal that without action, no such layers appear in 3D.
It would be nice to have this feature.

**Comment by jmgomezpoveda** [comment]
Does it make sense to close the issue when the feature still does not work? (due to a limitation or a feature enhancement required)

**Comment by gberaudo** [comment]
@jmgomezpoveda the reason for closing is that the issue has been identified and the question answered. For tracking implementation of raster reprojection, there is this old issue: https://github.com/openlayers/ol-cesium/issues/37.
I hope it clarifies.

**Comment by RunBoo** [comment]
@gberaudo 
Hello, I am currently facing a similar issue and I am not sure if OLCesium currently does not support this feature. I hope you can help take a look.
I can load MVT services with EPSG:4326 coordinates on a 2D map using ol-cesium, but it doesn't work when switching to a 3D map. However, map services with EPSG:3857 coordinates all work fine. 
Here is my code:  [#1114 ](https://github.com/openlayers/ol-cesium/issues/1114)
Could you please help identify what might be causing the problem?
