### ISSUE TITLE
Build without OpenLayers?

### ISSUE THREAD

**Issue by draganpodvezanec** [openlayers/ol-cesium#439]
Hi,

Is there a way to build ol3cesium "standalone", i.e. without included OpenLayers (and even Cesium)?

Best Regards,
Dragan

**Comment by gberaudo** [comment]
Hi Dragan,

The Cesium code is not merged into OL3-Cesium so you are free to depend on the version you want in the way you like (though we only test with the latest stable version, each month).

For OL3 it is different: we compile OL3-Cesium together with OL3 and the resulting js file is the optimization of the whole codebase. As a consequence it is not possible to have an arbitrary version of OL3.

Out of curiosity, have you a different use case?
