### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by projet3dcarto** [openlayers/ol-cesium#441]
Hi,

I got some troubles running Cesium with OL3, I followed the example but got an error when running it:
Uncaught TypeError: ol.events.listen is not a function
    at olcs.Camera.setView_ (ol3cesium-debug.js:25975)
    at new olcs.Camera (ol3cesium-debug.js:25935)
    at new olcs.OLCesium (ol3cesium-debug.js:31692)
    at index.html:35

Seems to be relative to this line :  
var ol3d = new olcs.OLCesium({map: map}); // map is the ol.Map instance

(The example without the globe 3D works well)
Any one got this problem ?

**Comment by gberaudo** [comment]
Hi @projet3dcarto, I cannot reproduce your error. Which example are you writting about?
I just released a new version, could you please test with it?
