### ISSUE TITLE
Website is down.

### ISSUE THREAD

**Issue by Andrew-Dunn** [openlayers/ol-cesium#444]
http://openlayers.org/ol3-cesium/

![image](https://cloud.githubusercontent.com/assets/417197/23384609/dc1ceea6-fd9f-11e6-8b70-7919141d8029.png)

**Comment by gberaudo** [comment]
Thanks for reporting this. It appears the new URL is now http://openlayers.org/ol-cesium/ .

**Comment by Andrew-Dunn** [comment]
Was there a reason for the change? It seems to have actually broken quite a few projects, including tileserver-php.

**Comment by gberaudo** [comment]
The `ol3-cesium` repository still exists. What do you mean by `broken`?

**Comment by Andrew-Dunn** [comment]
It seems like they are linking directly to /ol3cesium

**Comment by gberaudo** [comment]
The http://openlayers.org/ol3-cesium/ site is only for presenting the project and hosting examples, the resources should be copied in each one's project.

**Comment by gberaudo** [comment]
We have completed the renaming of the project to `ol-cesium`. I will now close this issue.

**Comment by Andrew-Dunn** [comment]
At the very least you should fix the broken links at https://openlayers.org/ol-cesium/

**Comment by gberaudo** [comment]
Thanks for the feedback, that page is now up-to-date.
