### ISSUE TITLE
enableRotation is not useful

### ISSUE THREAD

**Issue by LZS1991** [openlayers/ol-cesium#447]
I set enableRotation in the View to be false,but when i  rotate in the Cesium and come back,the 2D map still have rotated.So how to destroy the  synchronization of rotatoin between 2D and 3D map?Thank you for any answer!

**Comment by gberaudo** [comment]
Indeed it is not possible at the moment. Closing as a duplicate of https://github.com/openlayers/ol-cesium/issues/436.
