### ISSUE TITLE
ImageStatic On ol3? 

### ISSUE THREAD

**Issue by take999kimo** [openlayers/ol-cesium#458]
I can use  **ol.source.TileImage** On ol3
But can't use   **ol.source.ImageStatic** On ol3 ? like the figure
If possible   can U give an example? thanks
![staicimage0nol3](https://cloud.githubusercontent.com/assets/28704991/26054822/ac79112e-39a0-11e7-8b15-33e424bf751e.jpg)

**Comment by gberaudo** [comment]
Hello, no this has not been implemented yet.

**Comment by take999kimo** [comment]
Thank you for your reply.
After the version may achieve this function?

**Comment by gberaudo** [comment]
Hi @take999kimo, I heard of no plan to add support for this by the community.
If your source data is in EPSG:4326 (lonlat), then it should be straightforward to add support in OL-Cesium by mapping the OL static source to https://cesiumjs.org/Cesium/Build/Documentation/SingleTileImageryProvider.html. I can give further guidance and reviews if someone is interested to work on this.

**Comment by take999kimo** [comment]
gberaudo, Thank U!
 
You mean I can use it
Cesium.SingleTileImageryProvider
To put the static image in the OpenLayers
As used
_**TerrainProvider = new Cesium.CesiumTerrainProvider ({
  Url: 'https://assets.agi.com/stk-terrain/world'
});**_
So as long as Cesium provides the Provider
Can be applied to ol3d

**Comment by gberaudo** [comment]
I mean that if your dataset is supported by Cesium `SingleTileImageryProvider`, then:
- either you can use it directly, without relying on OL-Cesium (need manual action in your app);
- or you can come up with a PR for detecting OpenLayer layers of type static image and if they are compatible with Cesium `SingleTileImageryProvider`, handle the conversion (once merged, synchronization will be automatic in your app).
