### ISSUE TITLE
Mapbox Vector Tiles in OL-Cesium

### ISSUE THREAD

**Issue by chseip** [openlayers/ol-cesium#463]
This is related to #374 I think.

I wanted to use Mapbox Vector Tiles in OL-Cesium, esp. for pitch and bearing. In 2D everything loads fine. A detailed description can be found on [stackexchange](https://gis.stackexchange.com/questions/240720/mapbox-vector-tiles-in-ol-cesium).

If OL-Cesium does not support MVT does it support GeoJSON or TopoJSON vector tiles? If not, are there any plans for this?

Thanks in advance :-)

**Comment by gberaudo** [comment]
@chseip, yes it all depends on what is supported by Cesium. I have no more information than #374; if you find something interesting please report it here.
