### ISSUE TITLE
Blinking screen in 3D mode

### ISSUE THREAD

**Issue by slavas62** [openlayers/ol-cesium#465]
In the latest version 1.27 in 3D mode, changing the coordinates of the point vector object (feature.getGeometry().setCoordinates([...]) or layer.getSource().addFeature(feature)) causes the entire screen to blink. How it can be fixed.
In 2D mode all ok.

Thanks in advance.

**Comment by gberaudo** [comment]
Thanks for reporting this @slavas62. Is it also blinking in 1.26?
The only changes from OL-Cesium 1.26 to 1.27 are the update of the dependencies.

**Comment by slavas62** [comment]
Today tested again. In version 1.26 all ok.

**Comment by gberaudo** [comment]
I tested version 1.26 with the vector example. I can see this blinking when clicking the "add/remove one vector layer" and "add/remove one feature" buttons.
It does not blink every time. I will not have time to dig into this, please let me know if you find something.

**Comment by slavas62** [comment]
Well, if anything I find a message.

**Comment by HeavenlyHost** [comment]
Just to add to this, see referenced issue #477

**Comment by mramato** [comment]
FYI, there is a chance this blinking was a Cesium issue which we just fixed in https://github.com/AnalyticalGraphicsInc/cesium/pull/5632

It will be part of Cesium 1.36 on August 1st.

**Comment by gberaudo** [comment]
Thank you @mramato, I confirm Cesium master fixes the blinking of the OL-Cesium vectors example.

To everyone: next month version of OL-Cesium will be tested against Cesium 1.36. If you need an updated Cesium in the meanwhile you can simply compile it.

**Comment by slavas62** [comment]
Everything works correctly. Thank you all. -- С уважением,Вячеслав Серебряков   03.08.2017, 15:25, "gberaudo" <notifications@github.com>:Closed #465 via #481.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by HeavenlyHost** [comment]
Ok, so this issue has been fixed, however the runtime performance is terrible. Run it in 2d mode and everything renders quick and snappy, switch to 2d and everything drops through the floor ???

**Comment by gberaudo** [comment]
@HeavenlyHost, the solution was to update Cesium: there is no change in `OL-Cesium` code. You may have find a performance regression.
