### ISSUE TITLE
Openlayers version

### ISSUE THREAD

**Issue by oufresh** [openlayers/ol-cesium#470]
Hello, I would like to use ol-cesium and I'm currently using ol 4.20 in my applicatio. Does ol-cesium integrates all the features of Openlayers?Do I have to wait for the 4.20? Are there some limitations?
thanks.

Greetings

**Comment by KillDragon** [comment]
Release 1.28 based on OL 4.1.1 and Cesium 1.34.

**Comment by oufresh** [comment]
Ok, is there a roadmap to use ol 4.2.0?

**Comment by gberaudo** [comment]
Hi @oufresh, I will update master with OL 4.2.0 today.
A new release of OL3-Cesium will happen next week once Cesium 1.35 is released.

**Comment by gberaudo** [comment]
See https://github.com/openlayers/ol-cesium/pull/472.
OL-Cesium is based on unmodified OpenLayers, so you can use any feature from OpenLayers present in the version used by OL-Cesium. That said, not everything is automatically synchronized from 2D to 3D, you might need some manual work for some use-cases.

**Comment by oufresh** [comment]
Hello! thank you very much. I'm going to wait for the new release because I already use it in our project.
