### ISSUE TITLE
About vr in ol-cesium

### ISSUE THREAD

**Issue by zebrainncu** [openlayers/ol-cesium#471]
Hi,
can we use vr in ol-cesium?

as below link
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Cardboard.html&label=Showcases

when i click vr button, it will shows up two view.

**Comment by gberaudo** [comment]
No there is no such feature in OL-Cesium. Do yo know how Cesium handles this under the hood?

**Comment by jmgomezpoveda** [comment]
Actually, it does work. I am enabling it as:

```
var scene = map.getCesiumScene();
scene.useWebVR = !scene.useWebVR;
```

Though I reckon for a satellite view (as it is my use case), results are pretty disappointing.

**Comment by gberaudo** [comment]
Thanks @jmgomezpoveda for sharing!

**Comment by zebrainncu** [comment]
Thanks @jmgomezpoveda for sharing!
