### ISSUE TITLE
Bug with ol.interaction.Draw

### ISSUE THREAD

**Issue by KorzhovDmitry** [openlayers/ol-cesium#474]
When I try to draw a point when I click, the point is added to the wrong place where I clicked. In 2D mode with interaction I see a blue dot under the cursor before clicking, in 3D mode I do not see this point.

**Comment by gberaudo** [comment]
Hi @KorzhovDmitry, thanks for the feedback.

The `ol.interaction.Draw` interaction uses what is called an `unmanaged layer` for the blue dot you see in 2D; it is an internal layer, not visible from outside of OpenLayers, which makes it impossible for `OL-Cesium` to find out automatically about it. See https://github.com/openlayers/openlayers/blob/aced192bcd3edb14e7da8e733945bcca3915c18f/src/ol/interaction/draw.js#L239.

With collaboration from OpenLayers interactions, it may be possible to add such support in `OL-Cesium`; for example, the interactions could expose the array of `unmanaged layers` they use.

Regarding the placement of the point `at the wrong place`, could you give details about what you did? Is the point correctly placed in 2D?

**Comment by KorzhovDmitry** [comment]
Hi @gberaudo, you can see my example where when you click in openlayers draws a red circle and in cesium draws black dot.
Link : [https://github.com/KorzhovDmitry/ol-cesium-ol.interaction.Draw-example](url)
When cliked in center area of map difference is small, when clicked in the area closer to the edges difference is very high.

**Comment by gberaudo** [comment]
Hi @KorzhovDmitry, the OpenLayers draw interaction is not supposed to trigger when you are in 3D.

The problem you see comes from the fact that you add the draw interaction *after* the creation of OL-Cesium. To fix it you should move the creation of OL-Cesium a few lines later.

**Comment by KorzhovDmitry** [comment]
Thanks @gberaudo, now i realized that use ol.interaction.Draw with 3D map it bad idea. For each mode, need use the tools of its library.
