### ISSUE TITLE
cross color

### ISSUE THREAD

**Issue by KillDragon** [openlayers/ol-cesium#476]
Render by floor
in the version 1.28 in 3D mode  causes cross color. How it can be fixed.
Thanks in advance.

![d](https://user-images.githubusercontent.com/15921876/28254732-1b9024ea-6ae2-11e7-9994-6088250146a7.jpg)

**Comment by gberaudo** [comment]
Hi @KillDragon, this is a Cesium issue. Please open a bug [there](https://github.com/AnalyticalGraphicsInc/cesium/issues).

**Comment by KillDragon** [comment]
Thank you for your prompt reply
