### ISSUE TITLE
Layer's opacity is not updated.

### ISSUE THREAD

**Issue by oterral** [openlayers/ol-cesium#479]
In the case of you're using Cesium over the ol map , the visibility of the root group of the map is [set to false](https://github.com/openlayers/ol-cesium/blob/master/src/olcesium.js#L543) . This behavior, combined with the enabling of the auto render loop process,  prevents the layer's opacity  to be updated if the render loop is stopped.

If the root group has a visibility of false, [the change event is not propagated](https://github.com/openlayers/openlayers/blob/v4.2.0/src/ol/layer/group.js#L83)  and [catched by ol-cesium](https://github.com/openlayers/ol-cesium/blob/master/src/autorenderloop.js#L186)

You can reproduce it using the rastersync example in this zip file:
[rastersync.zip](https://github.com/openlayers/ol-cesium/files/1187048/rastersync.zip)

**Comment by gberaudo** [comment]
Fixed in newer OpenLayers version, see https://github.com/openlayers/openlayers/pull/7073.
