### ISSUE TITLE
OpenLayers v4.3.1

### ISSUE THREAD

**Issue by sergkr** [openlayers/ol-cesium#486]
Any chance a new version of ol-cesium could be pushed out that includes OpenLayers v4.3.1? I see the change has been made already in master (#431), it just hasn't been released yet.

**Comment by gberaudo** [comment]
Hi @sergkr, I will publish a new version of ol-cesium next week as soon as Cesium published its monthly stable version.

**Comment by sergkr** [comment]
Awesome, thanks!

**Comment by gberaudo** [comment]
v4.3.2 is now used in the latest release.
