### ISSUE TITLE
Error loading mapbox vector tiles (vector.pbf)

### ISSUE THREAD

**Issue by slavas62** [openlayers/ol-cesium#491]
In the new version OL3-Cesium v1.31, the vector tiles of the mapbox (format PBF) are not loaded in 2D mode (Error: Unimplemented type: 3    olcesium-debug.js: 65364). In the previous version of OL3-Cesium v1.30 in 2D mode everything was loaded without problems.

**Comment by gberaudo** [comment]
Hi @slavas62, the issue you reported is in OpenLayers itself, probably introduced with https://github.com/openlayers/openlayers/pull/7187. You should directly open the issue in the OpenLayers project, so I am closing it here.

**Comment by ahocevar** [comment]
openlayers/openlayers#7187 is not in any released Version of OpenLayers. Does ol-cesium 1.31 use OpenLayers from master?

**Comment by ahocevar** [comment]
@slavas62, can you please provide a full stack trace from a debug build?

**Comment by slavas62** [comment]
For each requested tile, an error is generated

Uncaught Error: Unimplemented type: 3
    at Pbf.skip (olcesium-debug.js:65364)
    at Pbf.readFields (olcesium-debug.js:65235)
    at new VectorTileLayer$1 (olcesium-debug.js:66059)
    at readTile (olcesium-debug.js:66098)
    at Pbf.readFields (olcesium-debug.js:65234)
    at new VectorTile$1 (olcesium-debug.js:66094)
    at ol.format.MVT.readFeatures (olcesium-debug.js:66459)
    at ol.VectorTile.<anonymous> (olcesium-debug.js:52200)

Here print screen debug window: https://drive.google.com/open?id=0B5dpmLRGImYtTkpjOFRnV1pseVk

**Comment by gberaudo** [comment]
@ahocevar, we are using the latest stable release: v4.3.2. But users compiling the library themselves can choose any other version (assuming it compiles).

**Comment by ahocevar** [comment]
Ok, the stack trace and @slavas62's comment indicate that the error is with OpenLayers v4.3.2, so it is not related to openlayers/openlayers#7187.

@slavas62, do you have that application (with a debug build of ol-cesium) available for debugging somewhere?

**Comment by slavas62** [comment]
@ahocevar, published application with a debug build of ol-cecium I do not. I'll try to prepare a separate publication and let you know later.

**Comment by slavas62** [comment]
I'm very sorry, the problem is solved. Our proxy cut off the response of the request for vector tiles. Once again sorry. Thanks to all.

**Comment by take999kimo** [comment]
Ol-Cesium：v1.36-3-g7788dbb
Openlayers：v4.4.2
wehn I use  addlayer  VectorTile (vector.pbf)
can not display in 3D
the error  let me  can not remove  the layer in 2D
so this version  not support  VectorTile  synchronize 2D/3D? 
error response
---------------------------------------------------
> olcesium.js:223 Uncaught TypeError: e.Od is not a function
>     at Li.k.bj (olcesium.js:223)
>     at Si.k.Me (olcesium.js:226)
>     at jc (olcesium.js:37)
>     at Si.<anonymous> (olcesium.js:40)
>     at kb.b (olcesium.js:16)
>     at kb.ab.dispatchEvent (olcesium.js:19)
>     at kb.k.ef (olcesium.js:23)
>     at kb.k.push (olcesium.js:23)
>     at Y.k.Ie (olcesium.js:315)
>     at MVTTiles (overlay.js:686)
------------------------------------------------
