### ISSUE TITLE
is Layer Cluster  is doesn't work?

### ISSUE THREAD

**Issue by wYuanHpp** [openlayers/ol-cesium#493]
when I use ol3 to build my project ,every thing is cool and worked.But when I try to  add olcesium to my project, I find my layer's Cluster  hasn't any feature , so my map doesn't display any feature.but this cluster's source has the right number features. I don't know why, help me thank you!

**Comment by gberaudo** [comment]
Hi @wYuanHpp, at the moment there is no support for clustering in OL-Cesium.
