### ISSUE TITLE
Overlays have no fixed position on globe

### ISSUE THREAD

**Issue by fcornelius** [openlayers/ol-cesium#506]
When adding an Overlay to the 2d map mith
```javascript
var pos = ol.proj.fromLonLat([16.3725, 48.208889]);

var marker = new ol.Overlay({
  position: pos,
  positioning: 'center-center',
  element: document.getElementById('marker'),
  stopEvent: false
});
map.addOverlay(marker);
```

the overlay is not fixed on the 3d map but moves around when the globe is rotated. Is there any conversion of the LongLat neccesary to be compatible with the 3d Map?

Thanks for your help

**Comment by gberaudo** [comment]
Hi @fcornelius, there is currently no support for overlays in OL-Cesium master. See the open PR https://github.com/openlayers/ol-cesium/pull/498.

**Comment by fcornelius** [comment]
Thanks for the quick response!

**Comment by jbo023** [comment]
@fcornelius gberaudo merged the Overlay functions to master, so you can check it out yourself, also you can probably close the issue.

**Comment by EzyBakeOven** [comment]
Is there any documentation on the overlay functions?

**Comment by jbo023** [comment]
@EzyBakeOven you can check the overlay Example: http://openlayers.org/ol-cesium/examples/overlay.html#
