### ISSUE TITLE
cloned ol-cesium code does not build. Errors out while doing "make dist"

### ISSUE THREAD

**Issue by d-bose** [openlayers/ol-cesium#519]
I followed the steps that have been given in the website
$ git clone --recursive https://github.com/openlayers/ol-cesium.git
$ make dist
$ make serve

But it does not go through. It errors out with "closure-util" in the message. I tried with multiple versions of node on multiple Mac computers and also in windows. For windows PC the error message is different.

Can you please fix the issue. So that we can build it?

Also, I was trying to get hold of the olcesium-debug.js But it seems that the file is not there. In your website it is written -
"Passing the parameter ?mode=dev to an example will load the debug version of Cesium instead of the minified one"
However, the link to olcesium-debug.js seem to be broken. - (http://openlayers.org/ol-cesium/olcesium-debug.js). Can you make that file available so that the examples can be run in debug mode?

Also, can you make the the "dist" folder available in git?

**Comment by gberaudo** [comment]
Hi @d-bose,

I am using GNU/Linux Ubuntu, the build works great on this environment.
Building on MacOS was also working (contributed from the community), but it may have broke.
I welcome contributions from the community to support more OSes.
Running a Linux distribution in a VM is an easy way to avoid these differences between OSes.

You are right, the olcesium-debug.js file is missing, I will open an issue about this.

The dist directory contains generated content, it should not be part of git (see the release zips if you want it already built).

**Comment by gberaudo** [comment]
@d-bose, you can find an olcesium-debug.js file in the ZIPs at https://github.com/openlayers/ol-cesium/releases.

**Comment by d-bose** [comment]
@gberaudo Thanks for you reply. Sorry for replying back to you late. We tried on a linux ubuntu machine also but that too gave a similar build error. I wish I could attach the screenshot but I could not get any option here to do so. The message says something like this.

```
npm ERR! Linux 4.13.6-16-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.11.4
npm ERR! npm v 3.5.2
npm ERR! ELIFECYCLE
npm ERR! closure-util@1.25.0 postinstall : 'node ./bin/closure-util.js update'
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the closure-util@1.25.0 postinstall script 'node ./bin/closure-util.js update'
```

**Comment by gberaudo** [comment]
During `closure-util` update, the GCC compiler and library are downloaded. Maybe you have some proxy preventing ZIP download?

**Comment by d-bose** [comment]
Thanks @gberaudo and sorry for a very late reply. Yes, it was indeed a proxy issue. I was successfully able to build it in ubuntu.
