### ISSUE TITLE
Errors with olcesium-debug.js 

### ISSUE THREAD

**Issue by maeg12** [openlayers/ol-cesium#523]
I installed the npm module version 1.32. 

1. I get the following error in the browser when using olcesium-debug.js (line 2969): `Error: TypeError: Cannot set property 'Error' of undefined`

2. I allready added openlayers to my application. There is also an error thrown, because some objects (e.g. `goog.provide('ol.array')`) are provided again within olcesium-debug.js

**Comment by gberaudo** [comment]
Hi @maeg12,

You need to remove OpenLayers from your application, ol-cesium already provides it.
Looking at the line you indicated I find no mention of Error, are you sure you are using 1.32?

**Comment by gberaudo** [comment]
Should now be the case with the new OL-Cesium 2.0 release.
