### ISSUE TITLE
 World Terrain Missing

### ISSUE THREAD

**Issue by cmdsevenai** [openlayers/ol-cesium#544]
World Terrain is not rendered in Scene. does anyone have ideas? Here are the work steps. 

**Step 1:**  Download release version from https://github.com/openlayers/ol-cesium
**Step 2**:  Execute sidebyside.html under Ol-cesium/examples/, which contains following files
* Inject_ol_cesium.js
* Sidebyside.js
* Sidebyside.html

### My result 
![grafik](https://user-images.githubusercontent.com/5315311/34719493-5cac1608-f53b-11e7-8242-8f90325b3b61.png)
### It should be like following
![grafik](https://user-images.githubusercontent.com/5315311/34719517-6e0bd424-f53b-11e7-9e97-2c169fae3122.png)

**Comment by gberaudo** [comment]
@cmdsevenai , you mean world imagery, right?
I tested using your steps and it displayed as expected.
Are you using an http server? I am using python:

```
~/Téléchargements/ol-cesium-v1.33$ python -m SimpleHTTPServer 4000
chromium localhost:4000/examples/sidebyside.html
```

**Comment by cmdsevenai** [comment]
@gberaudo Nice and it works now with http server. Thanks for your reply, really helpful.
