### ISSUE TITLE
Polygon outlines not working in Chrome

### ISSUE THREAD

**Issue by ediebold** [openlayers/ol-cesium#547]
For some reason polygon outlines do not seem to be visible in Cesium when using Chrome:
<img width="828" alt="screen shot 2018-01-23 at 1 44 23 pm" src="https://user-images.githubusercontent.com/3262375/35255580-d9e48642-0043-11e8-96a1-299ed67be0da.png">

Here is the same view in Safari (on the same computer):
<img width="830" alt="screen shot 2018-01-23 at 1 44 08 pm" src="https://user-images.githubusercontent.com/3262375/35255589-df5690ac-0043-11e8-8e2b-06853e6d7b97.png">

This doesn't seem to be a macOS issue either- I have tested Chrome on a Surface Pro and an Android phone, and neither could see the polygon outlines either.

Also to clarify, the height reference being used is "none".

I dug around the source code a bit, and it does seem to be the combination of PolygonOutlineGeometry and PerInstanceColorAppearance that doesn't render on the Chrome browsers.

**Comment by gberaudo** [comment]
Have you tried the sandcastle examples https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Polygon.html&label=Geometries ?

**Comment by ediebold** [comment]
I noticed some odd behaviour on that page, so I did a bunch of digging, and I think I've figured it out.

It seems that a bunch of browsers only support an aliased line width range of 1. The stroke width in my ol style was 2. This meant Safari (which on my machine supports an aliased line width range of 1 to 10) was able to display it, but Chrome could not.

I've added code on my end to limit the stroke width to 1 in ol, but it may be worth considering adding similar checks to createColoredPrimitive?

**Comment by gberaudo** [comment]
Line width aliasing is supposed to be handled by Cesium. See https://github.com/openlayers/ol-cesium/blob/9bc1bd7b86498c3628186f5019cab69a822953f4/src/olcs/featureconverter.js#L187.

Maybe there is a bug in Cesium. Could you check with the Cesium team?

**Comment by gberaudo** [comment]
@ediebold, what is the status regarding this issue? Can I close it?

**Comment by gberaudo** [comment]
Oops, clicked on the wrong button.
Please reopen if needed.
