### ISSUE TITLE
ImageWMS Synchronization

### ISSUE THREAD

**Issue by cmdsevenai** [openlayers/ol-cesium#550]
Hi ol-cesium, ImageWMS in ol.Map is not synchronized in Cesium 3d scene. 
I did it with `Cesium.WebMapServiceImageryProvider`. 
Is there any synchronization method?

**Comment by gberaudo** [comment]
Thanks for reporting that @cmdsevenai. See #552.

**Comment by cmdsevenai** [comment]
@gberaudo urw
