### ISSUE TITLE
ImageWMS example?

### ISSUE THREAD

**Issue by slavas62** [openlayers/ol-cesium#552]
Hi, the wms layer is not displayed in 3D mode http://openlayers.org/ol-cesium/examples/imageWMS.html.

**Comment by gberaudo** [comment]
Thanks @slavas62 for the report. It was fixed by https://github.com/openlayers/ol-cesium/pull/549. I will close your issue when a new release is published.

**Comment by slavas62** [comment]
Everything works perfectly. Thank you.
