### ISSUE TITLE
Is it possible to limit basemap's requests?

### ISSUE THREAD

**Issue by t1geomatika** [openlayers/ol-cesium#553]
I do some tests with ol-cesium and the result is great (thanks for this!)

When I play with the camera angle, more this angle is near 0 more ol-cesium loads tiles ( ok that's normal.. )
But, by example, with the following screen it loads around 1600 tiles (standard TMS 256*256).
Lot of them represent only 1px*1px on my screen. 
![v5_sat_3dgithub](https://user-images.githubusercontent.com/10755314/35930663-d5e3dcd2-0c32-11e8-8161-bcd3e2f33758.png)
Then, the map rendering become long. (It make moves nearly impossible)

My question: 

Is it possible to change a parameter to not load too far tiles? maybe with a blurred effect? 
Does somebody got the same problem?

Regards

**Comment by gberaudo** [comment]
Yes it is possible, see https://github.com/AnalyticalGraphicsInc/cesium/blob/0526709b31b178dd96006b975b4b9e0a6b0dbdc8/Source/Scene/Fog.js#L27-L45.

**Comment by isigeoinstall** [comment]
Thanks, it works ! 
<a href='https://cesium.com/blog/2015/11/12/fog/'>Cesium explains it here</a>

**Comment by t1geomatika** [comment]
Thanks, it works!
<a href='https://cesium.com/blog/2015/11/12/fog/'>Cesium describes it here</a>
