### ISSUE TITLE
Hability to load ol-cesium as a drop-in plugin

### ISSUE THREAD

**Issue by fnicollet** [openlayers/ol-cesium#555]
Hello and thanks for your work on this very interesting plugin,

I have a question regarding packaging, it is actually similar to a few issues posted here such as #439

I am having a hard time trying to make it work with our product. I replaced our version of OL (4.20) with the ol3cesium version but I get a weird behaviour (basically, the cesium globe only loads the 0/0/0 tile of my basemap and does not update when I move around or zoom in/out). I can't easily reproduce this issue on jsfiddle as the software which process the map is rather complicated.

So basically, I get a zoomable globe with one blurry tile and nothing happens, so I tried debugging, but the ol3cesium is all minified, so impossible to read or step-by-step (I guess I should use the .map files...).

But more importantly, the 3D viewer should be a plug-in features in our product: not bundled by default, but loaded on-the-fly. Because of the way ol-cesium is packaged, this seems impossible to do. I tried basically removing the OL goog.requires from your code, but then, it seems like ol-cesium uses some private OL APIs, such as "ol.events.listen" or even ol.math, which are not exposed by default by OL (which is probably why you had to package ol-cesium that way).

Our JS bundling is actually based on Google Closure, so I know that I can be a pain to do real "plug-ins", but do you think there is a way to make ol-cesium less dependant on OL somehow?

Thanks for your help,
Fabien

**Comment by gberaudo** [comment]
Hello @fnicollet, sorry I missed your question.

OL-Cesium is small so it should not be an issue for applications to always bundle it.
Cesium on the other hand is heavy and thus it is possible in OL-Cesium to lazy load it. See https://github.com/openlayers/ol-cesium/blob/master/src/olcs/contrib/manager.js.

In order to debug your issue, you can clone OL-Cesium, change the OpenLayers dependency to your custom one and run the examples. For the unminified mode, see https://github.com/openlayers/ol-cesium#running-the-unminified-version-of-cesium.

**Comment by fnicollet** [comment]
Thanks for your answer, all clear!

**Comment by fnicollet** [comment]
Just for anyone who would be looking to use ol-cesium as a plugin, it's not entirely impossible. You just have to create stub functions for goog.asserts functions and some OL function (ol.events.listen, ol.math.toRadians, ol.array, etc.).
Then change the call to getOptions_() to introspect the overlay (find in its set of keys, the one which has a map property in the minified properties, which is the options object).
Also, a couple of things are a bit tricky like getUid which has an internal counter in OL, not accessible in the release code, so you need to have your own getUid function.
I guess with a little effort on OL to make some method public, ol-cesium could be a standalone plugin. Someday :)

Fabien

**Comment by gberaudo** [comment]
Thanks for the feedback.
The "soon to be released" OL5 is going to rely on ES6 modules. Then integration with OpenLayers and OL-Cesium will be straightforward.

**Comment by fnicollet** [comment]
Do you mean that it will be possible to use ol-cesium as a plugin or that you will still need to build from source but it will be easier to do the build?

**Comment by gberaudo** [comment]
I mean it will be easier to build from source at it will integrate with build tools like webpack.

**Comment by fnicollet** [comment]
I see, thanks!
