### ISSUE TITLE
is drawing interaction supported on the 2d map？

### ISSUE THREAD

**Issue by LYF720** [openlayers/ol-cesium#567]
just like drawing interaction  in openlayer3，is it supported in ol_cesium，or how to realize it？

**Comment by gberaudo** [comment]
The standard OpenLayers library is used. As such, everything you can do with OpenLayers is available in 2d. For the same reason, everything you do yourself in 3d with Cesium is supported.

Regarding, the synchronization between 2d and 3d, you need to check what is currently implemented in OL-Cesium.

**Comment by LYF720** [comment]
much thanks! 
i'm working on OL-Cesium framework, to migrate old openlayers3 project to OL-cesium ,i'm afraid it is feasible or not.
