### ISSUE TITLE
ol-cesium + react

### ISSUE THREAD

**Issue by tt5430** [openlayers/ol-cesium#569]
I am interested to learn how to develop reactjs apps with ol-cesium but do not seem to find anything on the web talking about it.  Not sure if doing something like this is currently possible.  If yes, I'd greatly appreciate if someone give me some pointer.  If no, is there a plan for this in ol-cesium road map?

Regards,
Tam

**Comment by gberaudo** [comment]
Hi @tt5430, yes it is certainly possible to integrate ol-cesium or any js library in a react application.
For this you will need the ES6 module version of ol-cesium, see https://www.npmjs.com/package/olcs.

If you find out some concrete issue, please open a new issue.
