### ISSUE TITLE
about loading gltf 3Dmodel 

### ISSUE THREAD

**Issue by LYF720** [openlayers/ol-cesium#570]
now i come across another problem about loading gltf model, using entity.model = {uri:uri} method which has been realized in pure cesium, however, when  using the  same method in ol-cesium, there is an error shows 'runtime error failed to load......', and from the browser network i see the gltf model already been loaded finished, more important thing is popup windows show on map instead of gltf model after i checked the entity properties.

**Comment by gberaudo** [comment]
Do you have an extract of your code and a stack trace?

**Comment by LYF720** [comment]
sorry was busy those days, i debugged the code line by line, there is no error until set  entity.model property, and the gltf model is loaded into browser but doesn't show on globe.
now i find that if it is because the  ol3d.getOlView() is different from Cesium.Viewer(), or which can be used instead of Cesium.Viewer() in ol-cesium.

**Comment by LYF720** [comment]
finally, this problem has been solved  after i changed the version of Cesium.js, and checked the code where entity properties been setted. 
i think i need more patience.
