### ISSUE TITLE
Display correct credit information

### ISSUE THREAD

**Issue by SangeethaS94** [openlayers/ol-cesium#575]
In the latest version of ol-cesium, the credit information for the layers are not displayed correctly. The text, imageUrl and link parameters have been removed from Cesium.Credit in Cesium version 1.41 onwards. In the latest version of ol-cesium, three arguments are being passed when Credit object is created in function olcs.core.OLImageryProvider.createCreditForSource. In order to display the correct credit information, it must instead be one object that contains these three parameters.

**Comment by gberaudo** [comment]
Hi @SangeethaS94, I fixed the parameter passed to Cesium and opened #576 with the change. However there looks to still be some issues.

I will not have time in the next 3 weeks to look at this. If you investigate this, you are welcome to provide a pull request.

**Comment by gberaudo** [comment]
See also https://github.com/AnalyticalGraphicsInc/cesium/pull/6331.

**Comment by SangeethaS94** [comment]
Hi @gberaudo!
Thanks for looking into it. 

In my case, I changed

`return (imageUrl || text.length > 0) ? new Cesium.Credit(text, imageUrl, link) : null;`

to 

```
var options = new Object();
options.text = text;
options.imageUrl = imageUrl;
options.link = link;
return (imageUrl || text.length > 0) ? new Cesium.Credit(options) : null;
```

And everything seems to work well for me. I am not getting the issues you have mentioned in [#576](https://github.com/openlayers/ol-cesium/pull/576)

**Comment by gberaudo** [comment]
The issue I mentioned actually appears when the 3D globe is loaded first (not OpenLayers). This issue is unrelated to the OL and Cesium changes.
