### ISSUE TITLE
make dist failed

### ISSUE THREAD

**Issue by okflash** [openlayers/ol-cesium#577]
make dist
mkdir -p dist/
node build/build.js build/olcesium.json dist/olcesium.js
info ol-cesium Parsing dependencies
ERR! Could not find base.js
make: *** [dist/olcesium.js] Error 1

**Comment by gberaudo** [comment]
Hi @okflash, I tried with master and it worked.
Maybe there was an issue during "npm install", you should try again and reopen if you stil have the issue.
