### ISSUE TITLE
Cannot find module "ol/geom/Point.js"

### ISSUE THREAD

**Issue by jadelmag** [openlayers/ol-cesium#580]
I added ol-celsium to an project with openlayers 4.6.4 and show me this error:
`Cannot find module "ol/geom/Point.js" at Object../node_modules/olcs/OLCesium.js (OLCesium.js:1)`

I think that is an issue because **Point.js is in uppercase in ol-cesium** and **lowercase (ol/geom/point.js) in openlayers**.

I'm using react and following steps showed [here](https://www.npmjs.com/package/olcs) 
I have had to make ``npm run eject`` to create  webpack files and add an alias to the goog directory

    resolve: {
        alias: {
             'goog': '../node_modules/olcs/goog/',
        }
    }

You can see in this [example](https://codesandbox.io/s/8yzq194ny9)

![2018-04-24 10_38_45-react app](https://user-images.githubusercontent.com/1211066/39175896-ba132b20-47ab-11e8-8c44-16a63b0af5a7.png)

**Comment by gberaudo** [comment]
@jadelmag, see https://github.com/openlayers/ol-cesium/issues/456.
