### ISSUE TITLE
dependency @camptocamp/cesium has no 1.45.0 version

### ISSUE THREAD

**Issue by zhang90030** [openlayers/ol-cesium#589]
Now, the package.json file in the master branch write dependency
`"@camptocamp/cesium": "1.45.0"`
but, the repository in camptocamp has no the version 1.45.0 of cesium, why cesium dependency must use this repository, not AnalyticalGraphicsInc/cesium?

**Comment by gberaudo** [comment]
@zhang90030, version 1.45.0 is available on npm: https://www.npmjs.com/package/@camptocamp/cesium.

The camptocamp/cesium version is compatible with the upstream one and adds some features. See https://github.com/openlayers/ol-cesium/blob/37ba70999d8b9a11e2a345c04b15ccace8864b9b/CHANGES.md#v-131---2017-09-06

Note that it is a dev dependency, you are free to use whatever version you like in your project.
