### ISSUE TITLE
Installation from npm

### ISSUE THREAD

**Issue by willbreitkreutz** [openlayers/ol-cesium#590]
Hi, I might have missed something or it's just not clear in the docs, but when installing from NPM should we use the `olcs` or `ol-cesium` packages?  I'm assuming `ol-cesium`.   

On a related note, when referencing the openlayers package from the tarbal in order to use 5.x I have to use `import olMap from 'openlayers/src/ol/Map.js'` rather than the `import olMap from 'ol/Map'` as shown in the examples, not a big deal, but wanted to make sure I'm not missing something.  

I'm more than happy to submit a pull request updating the docs to clear up any ambiguity.

Thanks!

**Comment by gberaudo** [comment]
Yes you are right, you need to use `ol-cesium`. I did not update the experimental `olcs` package yet (maybe it should be discontinued?).

You should require OL code using `import olMap from 'ol/Map'`. You need a webpack alias for this.

If you can come up with a PR clarifying this it would be great.

**Comment by SCKgithub** [comment]
I am still not able to get the installation of packages right.
Can you please provide detailed procedure.
Like download and install ol-cesium
Copy ol 5 to ol directory etc....

When I provide all required library, the map doesn't appear from examples. I tried kml.html and kml.js
No errors
