### ISSUE TITLE
KML Feature Converter: Assertion failed

### ISSUE THREAD

**Issue by dandoteverest** [openlayers/ol-cesium#591]
Hello, I'm having an issue between the debug and non-debug versions when loading a KML file.  In non-debug, my KML file loads fine. However, when using the '-debug' version, I receive an 'Assertion Failed' that the text value of the style is undefined. This happens in the olcs.FeatureConverter.olGeometry4326TextPartToCesium method, which is called from 'olPolygonGeometryToCesium' method.

Essentially, the KML section that seems to be failing is the following:
`<Style>
  <PolyStyle>
    <color>9678dc00</color>
    <fill>l</fill>
    <outline></outline>
  </PolyStyle>
</Style>`

While I can work around it for now by using the non-debug version, I'd like to know if this error is correct. I cannot find anywhere that states a <text> tag is required inside a <Style> tag. So, before I go back to the people providing my KML, I'd like to know if this is a valid error condition.

Thanks.

**Comment by gberaudo** [comment]
@dandoteverest, it is hard to say without a running test case.
OL-Cesium is relying on the KML transformation implemented in OpenLayers. My guess is that an empty text style is created by OpenLayers. Could you please report if #592 is fixing your issue?
