### ISSUE TITLE
Stacked ground corridors for polygon outline

### ISSUE THREAD

**Issue by ediebold** [openlayers/ol-cesium#593]
The stacked ground corridors work great for polylines, but aren't implemented for polygon outlines. It'd be great if we could get this implemented in the same way.

**Comment by gberaudo** [comment]
Yes I guess it is possible to take all rings of a grounded polygon and create stacked ground corridors from them. PR welcome.

**Comment by ediebold** [comment]
Thanks. I'd had a quick look, but was scared off by the different structure of the polygon conversion code. I really need it though, so once I can get my issues in #594 fixed I'll give it a go.

**Comment by ediebold** [comment]
I was about to try and do this, but it looks like the next version of Cesium is going to include support for polylines on terrain: https://github.com/AnalyticalGraphicsInc/cesium/pull/6615

With that in mind, it probably makes more sense to wait for the next Cesium release and simply replace the stacked corridor code with support for the native polylines on terrain. After doing that, it shouldn't be too hard to use the same system for the polygon outlines.

So once the next Cesium release is out, I'll get to work on a PR for this.
