### ISSUE TITLE
can not addlayer VectorTile (vector.pbf) In 3D

### ISSUE THREAD

**Issue by take999kimo** [openlayers/ol-cesium#597]
Ol-Cesium：v1.36-3-g7788dbb
Openlayers：v4.4.2
wehn I use addlayer VectorTile (vector.pbf)
can not display in 3D
the error let me can not remove the layer in 2D
so this version not support VectorTile synchronize 2D/3D?
error response
------------------------------------------------------------------------
> olcesium.js:223 Uncaught TypeError: e.Od is not a function
> at Li.k.bj (olcesium.js:223)
> at Si.k.Me (olcesium.js:226)
> at jc (olcesium.js:37)
> at Si. (olcesium.js:40)
> at kb.b (olcesium.js:16)
> at kb.ab.dispatchEvent (olcesium.js:19)
> at kb.k.ef (olcesium.js:23)
> at kb.k.push (olcesium.js:23)
> at Y.k.Ie (olcesium.js:315)

**Comment by gberaudo** [comment]
Hello @take999kimo. see #374.
