### ISSUE TITLE
how it was done with webpack ?

### ISSUE THREAD

**Issue by Southjor** [openlayers/ol-cesium#601]
I did not find a way in the examples, and my english is terrible

**Comment by gberaudo** [comment]
Have you checked https://github.com/gberaudo/ol-cesium-webpack-example?
As you may have noticed, OpenLayers5 was released yesterday. I will try to have OL-Cesium ported next week.

**Comment by Southjor** [comment]
Thanks very much , i'll try it right away

**Comment by gberaudo** [comment]
Hi @Southjor, I updated the example project to OL5. It looks to work fine with current version of OL-Cesium (2.0).

That being said, I think I will be able to publish the 2.1 version of OL-Cesium next week (but that's also what I said 2 weeks ago!!).
