### ISSUE TITLE
terrain exaggeration with ol cesium 

### ISSUE THREAD

**Issue by Newton31** [openlayers/ol-cesium#614]
Is there a way to scale the terrain with ol cesium so as to increase artificially the relief ?

in cesium it seems possible from the Cesium.Viewer object thanks to the terrainExaggeration attribute
//Sandcastle_Begin
var viewer = new Cesium.Viewer('cesiumContainer', {
    terrainExaggeration : 2.0,
    terrainProvider: Cesium.createWorldTerrain()
});

is it possible to use this parameter with olcesium ?

Thank you, BR

**Comment by gberaudo** [comment]
See https://github.com/openlayers/ol-cesium/pull/325.
