### ISSUE TITLE
Incorrect or not generic enough 'goog' package path?

### ISSUE THREAD

**Issue by webarchymeta** [openlayers/ol-cesium#616]
I failed to compile the source using webpack in our project. All the file inside of the `src/olcs` sub-directory that depend on `goog/assert.js`  import it like this:
```
import googAsserts from 'goog/asserts.js';
```
however the `goog` package is under `src/goog` sub-directory. Therefor it seems 
```
import googAsserts from '../goog/asserts.js';
```
is the correct way of importing, unless of course `goog` is installed as a independent package, which apparently is not ...

**Comment by AlenKelemen** [comment]
For examples, I just compile using npm run build-examples or npm run serve for development server. Could you tell your complete procedure ?

**Comment by webarchymeta** [comment]
More details:

I was using `ol-cesium` in our own website, and indented to incorporating `ol-cesium` into our own libraries using command
```
npm install ol-cesium --save
```
to install it into the local project, then using import like the following to include `ol-cesium`:
```
import Map from 'ol/Map.js';
import View from 'ol/View.js';
import Feature from 'ol/Feature.js';
...
import OLCesium from 'ol-cesium/src/olcs/OLCesium.js';
import olcsCore from 'ol-cesium/src/olcs/core.js';
...
```
When I compile our own, it implies that the current working directory when including `ol-cesium` is `node_module\ol-cesium\src\olcs`, which does not have `goog` sub-directory, and therefor can not find the `goog/asserts.js` in our case.

The reason the current build script works (e.g. examples) is because it uses an entry point file `ol-cesium\src\index.library.js` so that the working directory is `ol-cesium\src` which contains the `goog` sub-directory. The problem is solved when made the changes mentioned in the previous message. There could be a better way ...

However, `ol-cesium\src\index.library.js`, which is
```
import OLCesium from './olcs/OLCesium.js';
export default OLCesium;
```
does not export all objects of  `ol-cesium`, e.g., the `core` (see above).

As a result, IMHO, the current way that the `goog` stuff is included is not generic enough to handle all possible customer lib importing scenarios ...

**Comment by gberaudo** [comment]
See the `goog` alias defined in https://github.com/openlayers/ol-cesium/blob/800a38738d83722b81ac3abd9b2f48b8e6a08891/buildtools/webpack.commons.js#L84.

The advantage in keeping goog absolute is that the user can switch the implementation with another one. For example in development having asserts actually checking arguments and in production mode optimizing it out.

**Comment by webarchymeta** [comment]
OK, I see ...

But still, I belief keeping the redirection in webpack config is not ideal since people like me who has our own webpack config and import selections may not know it at first and will think there is something wrong or missing in the library, which is literally true ...

**Comment by gberaudo** [comment]
I agree with you. Ideally there would be a `goog` package providing a default implementation for these `goog` functions. Unfortunately the `goog` name is already used in `npm`.
