### ISSUE TITLE
Incorrect Behavior with 3D tiles

### ISSUE THREAD

**Issue by bbehling** [openlayers/ol-cesium#623]
Trying to load 3D Tiles either with b3dm or point cloud data, and OL Cesium does not handle these requests correctly, and results in the 3D Tile not rendered on the map.

Comparing the request behavior between OL Cesium and Cesium using this [example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Feature%20Picking.html):

Cesium: First loads tileset.json file. Then another 13 b3dm files are loaded.
OL Cesium: Loads tileset.json, but loads 8 more of the same file and does not make any requests to get the b3dm files.

Below is a code example of how to make the request. 

```
const resource = new Cesium.Resource({
      url: 'https://assets.cesium.com/5741/tileset.json',
      queryParameters: {
        'access_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJhOWM4ZWFjMS1iMTI0LTRkOTctOGQxYy0wNDNkNjk3YWQ4ODEiLCJpZCI6MjU5LCJhc3NldHMiOnsiNTc0MSI6eyJ0eXBlIjoiM0RUSUxFUyJ9fSwic3JjIjoiYjBkYzNkMWItODgzNi00MzAxLThiZjktZjQ5ZGNkNjYxODI3IiwiaWF0IjoxNTMzNTkzMjU0LCJleHAiOjE1MzM1OTY4NTR9.-MViKdCDsNjP9i-hWWi6K3C3roqrqmgOA0Hl4zf77bk'
      },
   });
const tileset = new Cesium.Cesium3DTileset({ url: resource });
scene.primitives.add(tileset);
```

Similar issue when trying to load point clouds as in this example:
https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/gallery/3D%20Tiles%20Point%20Cloud.html

Appears maybe the Cesium3DTileset class is not processing the tileset file properly. Is OL Cesium not handling the tileset JSON response correctly?

**EDIT**: This is happening in an app using just Cesium. Will update with problem solved.

**Comment by bbehling** [comment]
Talked to Sean Lilley @ cesium, appears there is a breaking change in Cesium 1.48 and 3D Tiles. I was having the same problem in another not using ol-cesium until I upgrade to the latest NPM package.

Can ol-cesium be upgraded to use the latest Cesium build?

**Comment by bbehling** [comment]
Sean did provide the old asset number for a point cloud asset - 3838 (church in France).

That does not render correctly. That point cloud floats on the surface and other oddities. Maybe upgrading to latest Cesium will fix that?

**Comment by gberaudo** [comment]
Yes OL-Cesium was updated to use 1.48 yesterday.

**Comment by bbehling** [comment]
I upgraded to the latest ol-cesium version and there are still issues.

3Tiles based on b3dm work fine. 3D tiles based on point clouds have some issues. 

The point clouds load, but looks like the point cloud is not clamped to the ground correctly when using a terrain provider. Without using a terrain provider, the point cloud layer is positioned correctly.

To reduce produce this behavior, load the 3d tile point cloud with a terrain provider: 

```
const source = new olSourceOSM();

const ol2d = new olMap({
  layers: [
    new olLayerTile({
      source
    })
  ],
   target: 'map3d',
   view: new olView({
    center: olProj.transform([2.93, 46.39], 'EPSG:4326', 'EPSG:3857'),
    zoom: 19
  })
});

const ol3d = new OLCesium({
  map: ol2d,
  target: 'map3d',
  layers: []
});

const scene = ol3d.getCesiumScene();
scene.terrainProvider = Cesium.createWorldTerrain();

const tileset = new Cesium.Cesium3DTileset({ url: Cesium.IonResource.fromAssetId(5714) });
scene.primitives.add(tileset);
ol3d.setEnabled(true);
```

the cesium asset 5741, NYC buildings, work fine.

**Comment by gberaudo** [comment]
Have you tried with the Cesium version provided by OL-Cesium or directly using upstream?
Have you also tried outside of OL-Cesium?

**Comment by bbehling** [comment]
Tried this with the Cesium sandcastle example. Similar issues using only Cesium.

**Comment by bbehling-trimble** [comment]
Cesium says point clouds sometimes do not have elevation information. That info is usually added in the CLI process. 

They did provide an example on how to adjust Point Clouds elevation on the client, but that doesn't seem to be working either inside Cesium.

**Comment by bbehling-trimble** [comment]
Cesium fixed the point example:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Adjust%20Height.html

The behavior in ol-cesium is the same. Using their code sample to set the modelMatric property, the point cloud is not positioned correctly on the map.

I'm using the OLCesium.js library included in the examples.

**Comment by bbehling-trimble** [comment]
Setting the height properly as a translatation offset, then applying that to the modelMatrix will render the point correctly in ol-cesium.

```
const tileset = new Cesium.Cesium3DTileset({ url: Cesium.IonResource.fromAssetId(5714) });
scene.primitives.add(tileset);

tileset.readyPromise.then(function(tileset) {
      var cartographic = Cesium.Cartographic.fromCartesian(tileset.boundingSphere.center);
      var surface = Cesium.Cartesian3.fromRadians(cartographic.longitude, cartographic.latitude);
      var offset = Cesium.Cartesian3.fromRadians(cartographic.longitude, cartographic.latitude, 413);
      var translation = Cesium.Cartesian3.subtract(offset, surface, new Cesium.Cartesian3());

       tileset.modelMatrix = Cesium.Matrix4.fromTranslation(translation);
    }).otherwise(function(error) {
        console.log(error);
    });
```

**Comment by gberaudo** [comment]
Thanks for the explanations.

**Comment by groundrace** [comment]
Hello, I would reopen this, as in the meantime I've tested the usage of the modelMatrix (and adapted to recent Cesium version ) but it didn't work at all.
