### ISSUE TITLE
How to build single independent Cesium.js and use it in html in old fashioned way

### ISSUE THREAD

**Issue by kingofnull** [openlayers/ol-cesium#633]
I need to add the cesium and ol-cesium libs to an old project that use it's own js minifier  and and all js files should address statically without dynamic load of any other js. 
I try cesium old fashioned example but it load other cesium dependencies dynamically and I need a single file (un-minified one) of Cesium.js. If there is a way to build that single file that load statically please show me to do that.

**Comment by gberaudo** [comment]
Cesium relies on web workers that it loads dynamically.
You should ask this question on https://cesiumjs.org/forum/ .
