### ISSUE TITLE
But I am still facing issues with ol-cesium 2.2, KML not rendering on 3D

### ISSUE THREAD

**Issue by SCKgithub** [openlayers/ol-cesium#635]
I am using ol-cesium 2.2 with angular 6
Following are the warnings while compiling, can this cause any issue ?
WARNING in ./ol-cesium/dist/node_modules/ol/interaction/Draw.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* D:\Angular6Trial\NextGen3dWeb\ol-cesium\dist\node_modules\ol\interaction\Draw.js
    Used by 2 module(s), i. e.
    D:\Angular6Trial\NextGen3dWeb\ol-cesium\dist\node_modules\ol\interaction.js
* D:\Angular6Trial\NextGen3dWeb\ol-cesium\dist\node_modules\ol\interaction\draw.js
    Used by 2 module(s), i. e.
    D:\Angular6Trial\NextGen3dWeb\node_modules\@ngtools\webpack\src\index.js!D:\Angular6Trial\NextGen3dWeb\src\app\trn-analysis\trn-analysis-controller.component.ts

WARNING in ./ol-cesium/dist/node_modules/ol/layer/Vector.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* D:\Angular6Trial\NextGen3dWeb\ol-cesium\dist\node_modules\ol\layer\Vector.js
    Used by 20 module(s), i. e.
    D:\Angular6Trial\NextGen3dWeb\ol-cesium\dist\node_modules\ol\layer.js
* D:\Angular6Trial\NextGen3dWeb\ol-cesium\dist\node_modules\ol\layer\vector.js
    Used by 5 module(s), i. e.
    D:\Angular6Trial\NextGen3dWeb\node_modules\@ngtools\webpack\src\index.js!D:\Angular6Trial\NextGen3dWeb\src\app\map\map.component.ts

WARNING in ./ol-cesium/dist/node_modules/ol/source/Vector.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* D:\Angular6Trial\NextGen3dWeb\ol-cesium\dist\node_modules\ol\source\Vector.js
    Used by 23 module(s), i. e.
    D:\Angular6Trial\NextGen3dWeb\ol-cesium\dist\node_modules\ol\source.js
* D:\Angular6Trial\NextGen3dWeb\ol-cesium\dist\node_modules\ol\source\vector.js
    Used by 5 module(s), i. e.
    D:\Angular6Trial\NextGen3dWeb\node_modules\@ngtools\webpack\src\index.js!D:\Angular6Trial\NextGen3dWeb\src\app\map\map.component.ts
i ｢wdm｣: Compiled with warnings.

**Comment by gberaudo** [comment]
These are OpenLayers files.

**Comment by SCKgithub** [comment]
Can you please provide me step by step guide on how to use new ol-cesium
2.2 version without webpack
Earlier, ol3cesium was so straight forward, but now with version, I am not
able to run the examples.
I want to use this using import libraries and not webpack and common.js

**Comment by SCKgithub** [comment]
Are you available online now ?
