### ISSUE TITLE
Get reference to Cesium Viewer

### ISSUE THREAD

**Issue by bbehling** [openlayers/ol-cesium#648]
I'd like to request a new feature . Is it possible to get a reference to the Cesium viewer?

We need access to viewer to viewer properties such as

```
viewer.screenSpaceEventHandler
this.viewer.camera.flyTo({
  destination : rectangle
});
```

**Comment by gberaudo** [comment]
OL-Cesium is not using the Cesium viewer so what you ask is not possible.

That being said you can access the specific properties you want to use with:
- screenSpaceEventHandler => new Cesium.ScreenSpaceEventHandler(scene.canvas), see examples/synthvectors.js;
- camera.flyTo => ol3d.getCesiumScene().camera.flyTo.

**Comment by lzp0070007** [comment]
viewer.selectedEntity=entity     I want to   use  viewer.selectedEntity  in ol-cesium,there is other way???

**Comment by gberaudo** [comment]
@lzp0070007, there situation is the same, you need to implement it.
