### ISSUE TITLE
Error when it add an overlay

### ISSUE THREAD

**Issue by alvaroind** [openlayers/ol-cesium#650]
When an overlay is added following the example in: 

https://github.com/openlayers/ol-cesium/blob/master/examples/overlay.js

The following error appears:
![image](https://user-images.githubusercontent.com/37860823/45941386-32c1b280-bfde-11e8-86a6-e8aea4a8bc53.png)

It is related to the module indicated below:
![image](https://user-images.githubusercontent.com/37860823/45942371-6f8fa880-bfe2-11e8-9348-572b23c98c44.png)

I have checked if the module exists and does not exist in the open layer library for version 5.2.0. My solution has been to comment on the lines in which the module "ol_dom_js__WEBPACK_IMPORTED_MODULE_2__" appears, which appears "undefined".

I do not know exactly if this module affects other functionalities. If you suggest another solution or confirmation that it is correct, I would appreciate it.

**Comment by gberaudo** [comment]
Should be fixed by https://github.com/openlayers/ol-cesium/pull/656.
