### ISSUE TITLE
Why destroy is useless here?

### ISSUE THREAD

**Issue by vipcxj** [openlayers/ol-cesium#661]
https://github.com/openlayers/ol-cesium/blob/3ac805d5d04d40329ac1d2a9f2937f2d4d6ea439/src/olcs/VectorSynchronizer.js#L58

The parameter `destroy` is useless here.

**Comment by gberaudo** [comment]
@vipcxj, I do not understand. Could you elaborate?

**Comment by vipcxj** [comment]
@gberaudo 
whether the parameter `destroy` is true or false, the object is destroyed. The parameter `destroy` is useless here.

**Comment by gberaudo** [comment]
@vipcxj, the `destroy` parameter is used the line after: `this.csAllPrimitives_.destroyPrimitives = destroy;`.
The meaning of this is:
- destroy the Cesium wrapper object;
- ask Cesium to remove the Cesium primitive from the list of primitives;
- Cesium will destroy the object if `destroy` is `true`, will keep it alive if it is `false`.

**Comment by vipcxj** [comment]
@gberaudo 
But even `destroy` is `false`, `object.destroy()` is invoked here!

**Comment by gberaudo** [comment]
Yes, because we always destroy our wrapper.
On the contrary, the underlying Cesium object is only destroyed when `destroy` is true.
