### ISSUE TITLE
ol-cesium: error on converting ol application to 3d

### ISSUE THREAD

**Issue by ema2000** [openlayers/ol-cesium#672]
Hi, im developing Gis application based on ol and I'm very interest into upgrate to GIS 3d applications.
I've found ol-cesium that is the faster way to do it. I've seen the exemples and I've tried to convert my application (ol based, last version) to a 3d using ol-cesium. 
I've added the code lines:

	const ol3d = new olcs.OLCesium({map: map}); 
	ol3d.setEnabled(false);

into the right position and if i use only the map (without added layers feature layers) it works but as soon as I add a feature layer like point line polygon  it doesn't work at all.
I've studied the issue #350 and declared limitation but I cannot solve.
My question is: 
Do you think ol-cesium will resolve the limitations?
because a complex GIS application based on ol has to work as it is on ol-cesium, if not the application has to be rewritten, debugged and tested with a large effort that can maybe  justify a new development   of a complete Cesium native application.

Thank you very much and best regards,
Emanuele

**Comment by gberaudo** [comment]
Hi @ema2000. Indeed the goal of OL-Cesium is to avoid writting the same application twice.
There are limitations though. Some are due to limitations of the OpenLayers library, others are less used features / lack of contribution.

The limitation in #350 is that unmanaged layers are not discoverable by OL-Cesium. So you should either:
- make them as "normal layers": `map.addLayer(theNormalLayer)`, see https://github.com/openlayers/ol-cesium/issues/350#issuecomment-382737044;
- or implement a custom synchronization (see the https://github.com/openlayers/ol-cesium/blob/master/src/olcs/AbstractSynchronizer.js).

The 2nd option would require:
- adding 2 methods on `OLCesium`: `synchronizeUnmanagedLayer(theUnmanagedLayer) / unSynchronizeUnmanagedLayer(theUnmanagedLayer)`;
- tracking their changes and updating their 3d counterparts.

Contribution welcomed if you go with the 2nd option.

**Comment by ema2000** [comment]
Hi, for example if I try with this example:

<!DOCTYPE HTML>
<html style="height: 100%; width: 100%; margin: 0; padding: 0;">
<head>
<meta http-equiv="content-type" content="text/html; charset=windows-1252">
<title>test</title>
<script src="js/jquery/jquery.js"></script>
<script src="ol/ol.js"></script>
<script src="resources/olcesium.js"></script>
<script src="./node_modules/@camptocamp/cesium/Build/CesiumUnminified/Cesium.js"></script>
<script src="js/bootstrap.min.js"></script>
<link rel="stylesheet" href="Styles/ol.css" type="text/css">
<link rel="stylesheet" href="Styles/bootstrap.min.css" type="text/css">
<link rel="stylesheet" href="Styles/ol.css" type="text/css">

<style>
#map {
  position: relative;
}

      
</style>
<script>

function initGIS() {	

	var LayerArray =[];
	
LayerArray.push(
		  new ol.layer.Tile({
			  source: new ol.source.OSM(),
			  title: 'OSM',
			  type: 'base',
		      visible: true
			})
  );


  
var map = new ol.Map({
        layers: LayerArray,
        target: 'map',
        view: new ol.View({
          center: [0, 0],
          zoom: 5
        })
	  });

//	map.addLayer(clusters);
var geometry = new ol.geom.Polygon([
    [ [10.689697265625, -25.0927734375], [34.595947265625, -20.1708984375], [38.814697265625, -35.6396484375],
      [13.502197265625, -39.1552734375], [10.689697265625, -25.0927734375] ]
]);
geometry.transform('EPSG:4326', 'EPSG:3857');

var vectorLayer = new ol.layer.Vector({
    source: new ol.source.Vector({
        features: [new ol.Feature({
            geometry: geometry
        })]
    })
});

	map.addLayer(vectorLayer);

	const ol3d = new olcs.OLCesium({map: map}); 
	ol3d.setEnabled(false);

	document.getElementById('enable').addEventListener('click', () => ol3d.setEnabled(!ol3d.getEnabled()));

}


</script>

</head>
<body onload="initGIS()" style="height: 100%; width: 100%;">
<div id="map" class="map" style="height: 100%; width: 100%;">
<input id="enable" type="button" value="2D/3D" />
</div>
</body>
</html>

if I comment the line

 map.addLayer(vectorLayer);

it works (of course the polygon is not shown) and draw the Cesium 3d map .

the error is on :

asserts.js:6 Uncaught TypeError: Right-hand side of 'instanceof' is not an object
    at Object.assertInstanceof (asserts.js:6)
    at VectorSynchronizer.createSingleLayerCounterparts (VectorSynchronizer.js:106)
    at _loop (AbstractSynchronizer.js:127)
    at VectorSynchronizer.addLayers_ (AbstractSynchronizer.js:100)
    at VectorSynchronizer.synchronize (AbstractSynchronizer.js:77)
    at new OLCesium (OLCesium.js:217)
    at initGIS (test1.html:65)
    at onload (test1.html:76)


at the instruction: 

  synchronize() {
    this.destroyAll();
    this.addLayers_(this.mapLayerGroup);

where is the problem?
thank you very much
Emanuele

**Comment by ema2000** [comment]
sorry for the code presentation, 

<!DOCTYPE HTML>
<html style="height: 100%; width: 100%; margin: 0; padding: 0;">
<head>
<meta http-equiv="content-type" content="text/html; charset=windows-1252">
<title>test</title>
<script src="js/jquery/jquery.js"></script>
<script src="ol/ol.js"></script>
<script src="resources/olcesium.js"></script>
<script src="./node_modules/@camptocamp/cesium/Build/CesiumUnminified/Cesium.js"></script>
<script src="js/bootstrap.min.js"></script>
<link rel="stylesheet" href="Styles/ol.css" type="text/css">
<link rel="stylesheet" href="Styles/bootstrap.min.css" type="text/css">
<link rel="stylesheet" href="Styles/ol.css" type="text/css">

<style>
#map {
  position: relative;
}

      
</style>
<script>

function initGIS() {	

	var LayerArray =[];
	
LayerArray.push(
		  new ol.layer.Tile({
			  source: new ol.source.OSM(),
			  title: 'OSM',
			  type: 'base',
		      visible: true
			})
  );


  
var map = new ol.Map({
        layers: LayerArray,
        target: 'map',
        view: new ol.View({
          center: [0, 0],
          zoom: 5
        })
	  });

//	map.addLayer(clusters);
var geometry = new ol.geom.Polygon([
    [ [10.689697265625, -25.0927734375], [34.595947265625, -20.1708984375], [38.814697265625, -35.6396484375],
      [13.502197265625, -39.1552734375], [10.689697265625, -25.0927734375] ]
]);
geometry.transform('EPSG:4326', 'EPSG:3857');

var vectorLayer = new ol.layer.Vector({
    source: new ol.source.Vector({
        features: [new ol.Feature({
            geometry: geometry
        })]
    })
});

	map.addLayer(vectorLayer);

	const ol3d = new olcs.OLCesium({map: map}); 
	ol3d.setEnabled(false);

	document.getElementById('enable').addEventListener('click', () => ol3d.setEnabled(!ol3d.getEnabled()));

}


</script>

</head>
<body onload="initGIS()" style="height: 100%; width: 100%;">
<div id="map" class="map" style="height: 100%; width: 100%;">
<input id="enable" type="button" value="2D/3D" />
</div>
</body>
</html>

**Comment by ema2000** [comment]
`

function initGIS() {	
var LayerArray =[];
LayerArray.push(
		  new ol.layer.Tile({
			  source: new ol.source.OSM(),
			  title: 'OSM',
			  type: 'base',
		      visible: true
			})
  );
var map = new ol.Map({
        layers: LayerArray,
        target: 'map',
        view: new ol.View({
          center: [0, 0],
          zoom: 5
        })
	  });
var geometry = new ol.geom.Polygon([
    [ [10.689697265625, -25.0927734375], [34.595947265625, -20.1708984375], [38.814697265625, -35.6396484375],
      [13.502197265625, -39.1552734375], [10.689697265625, -25.0927734375] ]
]);
geometry.transform('EPSG:4326', 'EPSG:3857');
var vectorLayer = new ol.layer.Vector({
    source: new ol.source.Vector({
        features: [new ol.Feature({
            geometry: geometry
        })]
    })
});
	map.addLayer(vectorLayer);

	const ol3d = new olcs.OLCesium({map: map}); 
	ol3d.setEnabled(false);

	document.getElementById('enable').addEventListener('click', () => ol3d.setEnabled(!ol3d.getEnabled()));
}

`

I don't know why it doesn't visualize well.

**Comment by gberaudo** [comment]
You are not using ES6 modules, right? Are you using latest version of OL-Cesium?
See https://github.com/openlayers/ol-cesium/issues/613.

**Comment by gberaudo** [comment]
I am not aware of anyone working on this.

**Comment by ema2000** [comment]
Hello,
I'm still working on ol-cesium and I would like to ask:
- To move from 2d to 3d on an already developed openlayers application should use olcs or not (interactions, some layers)? or it is faster rewrite on cesium?
- Is it possible by analyzing the openlayers code to know in advance which parts will not work on olcs?
- Is it possible at least not make the olcs layer go wrong and then maybe add the non-working parts to the cesium layer by hand?

I have a quite good knowledge of openlayers but not Cesium, so I do not think I can contribute to the development of olcs but I would like to be able to somehow manage the opelayers code in a complete way to not fail when you add

```
const ol3d = new olcs.OLCesium({map: map}); 
ol3d.setEnabled(false);

```
and try to reuse most of the code already written in openlayers
thank you and regards,
Emanuele

**Comment by gberaudo** [comment]
If you are fine with the functionalities and performance of Cesium in 2d and 3d then you should consider rewriting your application for Cesium.

If you want to keep OpenLayers for 2d and only use Cesium for 3d then OL-Cesium should be the most straightforward way.

OpenLayers as many features and ways to be used so it is hard to say if you will encounter (many) issues or not. That being said, these are not supported:
- interactions;
- raster reprojection.

You are free to manually add any layer / model / to Cesium. OL-Cesium will not interfere with them.
You can also override the OL-Cesium synchronizers to have custom transformation.

**Comment by ema2000** [comment]
Thank you for your answer I will continue to study about ol-cesium.
regards, 
Emanuele
