### ISSUE TITLE
olcesium token use

### ISSUE THREAD

**Issue by jfozzi** [openlayers/ol-cesium#674]
Hi,

I am using cesium ion token in my geoserver/openlayers application, 3D and terrain are working but I still have the message " This application is using Cesium's default ion access token. Please assign Cesium.Ion.defaultAccessToken with an access token from your ion account before making any Cesium API calls. You can sign up for a free ion account at https://cesium.com"

thanks for the help

**Comment by gberaudo** [comment]
@jfozzi, I don't see such messages in the OL-Cesium examples.
You probable set the token incorrectly and should inspect the requests sent to Cesium servers to check what token is used.

**Comment by jfozzi** [comment]
Hi, 
the token works when I create a cesium viewer in openlayers but then terrain doesn't work. (I place the token before "ol2d") but when I use "const ol3d = new olcs.OLCesium...) with the token I got a black screen (but cesium ion appears, without token it works but I have de message "please assign...")
The only error message is this: (dont know why)

 Échec du chargement pour l’élément <script> dont la source est « http://10.31.2.102/node_modules/@camptocamp/cesium/Build/Cesium/Cesium.js ».

**Comment by jfozzi** [comment]
Hi,

Problem solved, the token was set incorrectly as you said now it works, thanks!
