### ISSUE TITLE
Exclude OL vector tile layers from synchronisation attempt to avoid errors

### ISSUE THREAD

**Issue by mschulz-716** [openlayers/ol-cesium#689]
Hello,

 as already discussed e.g. in https://github.com/openlayers/ol-cesium/issues/374 there is currently no support for OL vector tile layers. Nevertheless we would like to use ol-cesium although we have a vector tile layer besides other vector and raster layers but just want to exclude this layer from synchronisation. Since currently an error appears when VectorSynchroniser tries to handle a vector tile layer the simplest way to achieve this seems to be to change VectorSynchronizer slightly to ignore vector tile layers. The necessary small changes I suggest can be found in this commit in my fork:
https://github.com/mschulz-716/ol-cesium/commit/e478116ce0f57bd3e4cc734d91d1098d95631144
Would you be interested to include these changes to your master branch as long as vector tile layers are not supported?

Thank you very much for looking into this,

Matthias

**Comment by gberaudo** [comment]
Hi @mschulz-716, yes it is a reasonable change. Please create a PR.
