### ISSUE TITLE
Examples broken?

### ISSUE THREAD

**Issue by ksrb** [openlayers/ol-cesium#699]
A bunch of the examples seem to be broken at https://openlayers.org/ol-cesium/examples.

Related issue https://github.com/openlayers/ol-cesium/issues/585

**Comment by ksrb** [comment]
For people trying to get the examples to work you can do:

```bash
git clone https://github.com/openlayers/ol-cesium
cd ol-cesium
npm install && npm serve
```

**Comment by gberaudo** [comment]
It is now fixed. That was due to a change in github handling of gh-pages.
