### ISSUE TITLE
Question about calcDistanceForResolution

### ISSUE THREAD

**Issue by ksrb** [openlayers/ol-cesium#700]
Specifically this line: 
https://github.com/openlayers/ol-cesium/blob/b78d0fef90049136a833d969e8e49e5a81a3dd56/src/olcs/Camera.js#L466

Was there a particular reason why the average of `clientHeight` and `clientWidth` wasn't used? Changing the code to:
```js
  const visibleMapUnits = (resolution * (canvas.clientWidth + canvas.clientHeight)) / 2;
```

Just wondering cause it would be more accurate on average? Unless users only tend to move their map up and down.

Function linked for reference:
https://github.com/openlayers/ol-cesium/blob/b78d0fef90049136a833d969e8e49e5a81a3dd56/src/olcs/Camera.js#L459-L490

**Comment by gberaudo** [comment]
@ksrb, the computation relies on the fov value. Cesium has only an accessor for the fovy. So we only use the client height.

**Comment by ksrb** [comment]
Okay that makes sense thanks.
