### ISSUE TITLE
Whether WMTS loading is supported

### ISSUE THREAD

**Issue by zl142900** [openlayers/ol-cesium#703]
Hello, why did the 2d loading of WMTS succeed but the 3d loading did not

**Comment by gberaudo** [comment]
I have added a WMTS example, see https://github.com/openlayers/ol-cesium/pull/704.
Ping back #453.

**Comment by zl142900** [comment]
![image](https://user-images.githubusercontent.com/42824619/56571368-5e962c80-65ef-11e9-8d5f-c165e3ec7eeb.png)
![image](https://user-images.githubusercontent.com/42824619/56571383-65bd3a80-65ef-11e9-8a74-06039cc2499d.png)


Why didn't that happen

**Comment by zl142900** [comment]
WMTS are not loaded when switching to 3d
![image](https://user-images.githubusercontent.com/42824619/56573091-f21d2c80-65f2-11e9-9c3b-4c98037eee81.png)

**Comment by gberaudo** [comment]
It works on my side:
make serve
open http://localhost:3000/examples/wmts.html
![image](https://user-images.githubusercontent.com/7294662/56575781-f29fce00-65c6-11e9-8033-6c0b1634d038.png)

**Comment by zl142900** [comment]
Can you post this demo somewhere I can access, for example：
![image](https://user-images.githubusercontent.com/42824619/56625644-db1d1f80-6670-11e9-8111-4fbdd980bc6e.png)

**Comment by gberaudo** [comment]
@zl142900, it was merged in master, see https://github.com/openlayers/ol-cesium/pull/704.

**Comment by zl142900** [comment]
@gberaudo I copied your code but I still couldn't, as I said above, not load in 3d.Do you have a solution?

**Comment by gberaudo** [comment]
@zl142900, there must be something different in your setup compared to the example.
What projection are you using?

**Comment by zl142900** [comment]
EPSG:4326

**Comment by gberaudo** [comment]
@zl142900, OK then projection should not be the issue.

**Comment by zl142900** [comment]
I can't load any other WMTS,，But it loads WMS, XYZ, OMS

**Comment by zl142900** [comment]
this problem is not cross-domain when loading WTMS in 2d, but cross-domain when loading WTMS in 3d. How to solve it
