### ISSUE TITLE
3dmap did not show ，use vue +webpack

### ISSUE THREAD

**Issue by ErichChen** [openlayers/ol-cesium#707]
![image](https://user-images.githubusercontent.com/21305978/58238700-56f6ae80-7d7a-11e9-921e-cb4648650298.png)

if i just use cesium ，the map is show

but when use ol-cesium ，3dmap didnot work，with out any error

**Comment by xydwhaha** [comment]
did you fix it?,could you send me the code?

**Comment by liyilmaz** [comment]
did you fix it?

**Comment by SucroseStudio** [comment]
Don't use the latest version 6.0.0 of openlayers, downgrading to version 5.3.3 may be helpful.

**Comment by ErichChen** [comment]
> 您解决了吗？您可以发给我密码吗？



> did you fix it?,could you send me the code?

**Comment by ErichChen** [comment]
> did you fix it?,could you send me the code?

no，and you？

**Comment by ErichChen** [comment]
> did you fix it?

no，how about you

**Comment by ErichChen** [comment]
> Don't use the latest version 6.0.0 of openlayers, downgrading to version 5.3.3 may be helpful.

used 5.4.0，try other version later
