### ISSUE TITLE
Page not found for ol-cesuim API document

### ISSUE THREAD

**Issue by 269017583** [openlayers/ol-cesium#708]
Hi I try to open the API document page like "https://openlayers.org/ol-cesium/apidoc/modules/_index_library_.html"  but it was 404 ERROR now.  
could anyone can fix it please?

**Comment by gberaudo** [comment]
Thanks, @269017583. It should now be fixed.

**Comment by gberaudo** [comment]
:( it broke the rest of the UI so I am reverting it.
You can see the API locally if you clone the repo and call `npm run doc` and open the apidoc folder.

**Comment by 269017583** [comment]
ok ， thanks. I‘ll take the loaclly way. wish you can fix the online doc. 
:) :) :)
