### ISSUE TITLE
Receiving TypeError: styles is null

### ISSUE THREAD

**Issue by pegues** [openlayers/ol-cesium#709]
When I enable instantiate OLCesium (var ol3d = new OLCesium({map: map});) and then do some kind of interaction with the OL map, I get the following error:

TypeError: styles is null

If I remove OLCesium from my project, I can interact with OL and never get the above TypeError notice.

Can someone help me with this?

**Comment by pegues** [comment]
The full list of the error is the following:

TypeError: styles is null bundle.js line 3025 > eval:1297:9
    convert webpack:///./node_modules/olcs/FeatureConverter.js?:1297
    onAddFeature webpack:///./node_modules/olcs/VectorSynchronizer.js?:150
    <anonymous> self-hosted:985
    createSingleLayerCounterparts webpack:///./node_modules/olcs/VectorSynchronizer.js?:190
    boundListener webpack:///./node_modules/ol/events.js?:51
    dispatchEvent webpack:///./node_modules/ol/events/Target.js?:104
    handleFeatureChange_ webpack:///./node_modules/ol/source/Vector.js?:864
    boundListener webpack:///./node_modules/ol/events.js?:51
    dispatchEvent webpack:///./node_modules/ol/events/Target.js?:104
    changed webpack:///./node_modules/ol/Observable.js?:47
    setStyle webpack:///./node_modules/ol/Feature.js?:244
    startAnimation webpack:///./Theme/js/app.js?:1356

**Comment by gberaudo** [comment]
Hello @pegues, you found a bug in OL-Cesium. I have opened a PR to fix the issue.
The issue is that you have a feature with a `null` style.

You can workaround the issue in your code by using an empty array instead of this `null` value.
