### ISSUE TITLE
Compatibility with OL6

### ISSUE THREAD

**Issue by remiHau** [openlayers/ol-cesium#725]
Hello,

I'm using openlayers and ol-cesium and I'm trying to update my application to the latest version of OL. I have trouble to make ol-cesium work with ImageLayer on the new version.

Do you know if there is a compatibility issue or if that should work as before? 

Thanks for your help.

**Comment by tomasregina** [comment]
Hello,
Did you solve that problem with ol-cesium and ol6 compatibility? I'm facing very similiar issue so I'm curious if there is any way how to solve it or if I should use ol5 instead.
Thanks for help!

**Comment by remiHau** [comment]
Yes there was a new tag 2.10 which works with ol6 but it's not tagged as a new release. I don't know why, maybe there is still work to do.
You can find it here : https://github.com/openlayers/ol-cesium/releases/tag/v2.10
