### ISSUE TITLE
how to add measuring tool  in 3D Model?

### ISSUE THREAD

**Issue by Caoshangyoung** [openlayers/ol-cesium#734]
hello,I know how to add a measurement tool in 2d mode, but how to measure in 3d mode.Can you show me an example? It seems that the cesium universal measurement method cannot be used here.Please reply as soon as you see it

**Comment by gberaudo** [comment]
Hi @Caoshangyoung, what do you mean with "cesium universal measurement method"?

**Comment by Cris-wang** [comment]
[emm]
