### ISSUE TITLE
API doc links are broken

### ISSUE THREAD

**Issue by kshea12** [openlayers/ol-cesium#739]
All API docs at https://openlayers.org/ol-cesium/apidoc/ result in a 404.

![image](https://user-images.githubusercontent.com/16846801/75563176-e3c04e00-5a17-11ea-8f4d-32f3333f0748.png)

**Comment by gberaudo** [comment]
Hi @kshea12, the link opens correctly on my side.
You can also clone the project and build the documentation: `npm i; make dist-apidoc`
