### ISSUE TITLE
OLCesium is not a constructor

### ISSUE THREAD

**Issue by gjvera** [openlayers/ol-cesium#745]
I'm having some issues getting started with ol-cesium. 

I have 
`import OLCesium from 'olcs/OLCesium.js'`
but whenever I get to 
`const ol3d = new OLCesium({ map }) `
I receive the following error
```_OLCesium2.default is not a constructor```
I'm using yarn for my project as opposed to npm. I'm not sure if that matters at all. 
I've looked around in the old issues and haven't been able to find a solution.

Any help would be appreciated.

**Comment by gberaudo** [comment]
Hi @gjvera, your code snippet looks correct.
I guess you are using a bundler (webpack, rollupJS, ...). There must be something wrong there but clearly unrelated to OL-Cesium so I am closing this issue.
