### ISSUE TITLE
scene.primitives.add don't work  background black

### ISSUE THREAD

**Issue by SergioAzCa** [openlayers/ol-cesium#769]
I am trying to load a 3d model into olcs but it doesn't show me anything on the map.
**I have this code:**

```js
 const ol3d = new OLCesium({
  map: map,
});
const scene = ol3d.getCesiumScene();
var worldTerrain = Cesium.createWorldTerrain({
  requestWaterMask: true,
  requestVertexNormals: true,
});
ol3d.setEnabled(true)

var origin = Cesium.Cartesian3.fromDegrees(-3.74922,39.463667, 200000.0);
const modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(origin);
scene.primitives.add(Cesium.Model.fromGltf({
    url:'./src/img/box/Box.glb',
    modelMatrix:modelMatrix,
    scene:scene,
    scale:100.0,
})); 
```

I get the black background without any soil

Thanks

**Comment by gberaudo** [comment]
Hi @SergioAzCa, usually Cesium gets black when it encounters an error.
Try using the debug version of Cesium, it will detect more errors and earlier.
In addition it is often easier to first test your code with pure CesiumJS and then integrate with OL-Cesium.
