### ISSUE TITLE
Getting Cesium.Viewer instance (for example: using Billboards case)

### ISSUE THREAD

**Issue by LinkFly** [openlayers/ol-cesium#772]
I want to get Cesium.Viewer instance (for using billboards, see cesium/Apps/Sandcastle/gallery/Billboards.html example)
But I also want to continue using OL-Cesium. If I to create Cesium.Viewer after initialization with OL-Cesium:
`var viewer = new Cesium.Viewer("cesiumContainer");`
... I is getting rendering error: "An error occurred while rendering.  Rendering has stopped."

**Comment by gberaudo** [comment]
Hello @LinkFly,

OL-Cesium is using the lower-level Primitive API. However you should be able to use the Entities API by getting a grab on the default datasource:
`OLCesium.getDataSourceDisplay().defaultDataSource.entities.add(...)`
See https://cesium.com/docs/cesiumjs-ref-doc/EntityCollection.html.
