### ISSUE TITLE
Is v2.11.0 not released on npm?

### ISSUE THREAD

**Issue by yiwenzhang666999** [openlayers/ol-cesium#778]

**Comment by yiwenzhang666999** [comment]
How is ol-cesium compatible with ol6? If ol6 is used, the map events on the 3D ball will not work?

**Comment by gberaudo** [comment]
Hello @yiwenzhang666999, it is listed there: https://www.npmjs.com/package/ol-cesium.

OL-Cesium should be compatible with OL6. Have you encountered some issues? Could you be more specific?

**Comment by yiwenzhang666999** [comment]
hello @gberaudo When I upgrade to ol6, the map mouse events are no longer available

**Comment by gberaudo** [comment]
Hi @yiwenzhang666999, are you using OL 6.4? There is something wrong with that version; OL 6.3 is working (see https://openlayers.org/ol-cesium/examples/main.html).

**Comment by yiwenzhang666999** [comment]
hi@gberaudo I tested it, and it is ok on ol6.3.1, but ol6.4 must be used for some reasons. Is it possible to solve the mouse event in ol6.4?

**Comment by gberaudo** [comment]
Fixed in 2.11.3.
