### ISSUE TITLE
Map interactions broken in 3D mode after OpenLayers 6.4 upgrade

### ISSUE THREAD

**Issue by Flowm** [openlayers/ol-cesium#781]
After upgrading from OpenLayers 6.3.1 to 6.4 map interactions (e.g. zoom, drag) don't seem to have any effect.

The ol-cesium examples appear to be affected by this too:
- Currently the openlayers version in `package.json` is set to `"ol": "^6.0.1",` which results in an openlayers version >6.4.
- Explicitly setting the openlayers version to `"6.3.1"` fixes map interactions in the olcs examples when testing locally
- Example: https://openlayers.org/ol-cesium/examples/main.html

**Comment by gberaudo** [comment]
Thank you @Flowm for reporting the issue. I published a version preventing installation of OL 6.4.

**Comment by gberaudo** [comment]
Hi @Flowm, I just published version 2.11.3 to fix this.

**Comment by Flowm** [comment]
Thanks @gberaudo! Everything is working perfectly again after the upgrade.
