### ISSUE TITLE
how to hide the "Cesium icon *****" on the 3D map?

### ISSUE THREAD

**Issue by akaishi3** [openlayers/ol-cesium#782]
we use 
     this.ol3d.getCesiumScene.viewer._creditContainer.display = 'none'
and
   <style>
.cesium-widget-credits {
  display: none !important;
  visibility: hide !important;
}
</style>

  but it dosnot work...

**Comment by akaishi3** [comment]
and  this desnot work also...

document.getElementsByClassName(
         'cesium-credit-logoContainer'
       )[0].style.visibility = 'hidden'
       document.getElementsByClassName(
         'cesium-credit-textContainer'
       )[0].style.visibility = 'hidden'
       document.getElementsByClassName(
         'cesium-credit-expand-link'
       )[0].style.visibility = 'hidden'
       document.getElementsByClassName(
         'cesium-credit-lightbox-overlay'
       )[0].style.visibility = 'hidden'

how to hiden the credit div?

**Comment by gisgaleno** [comment]
<style>
      .cesium-credit-textContainer,.cesium-credit-logoContainer,.cesium-credit-expand-link{ 
      display:none!important; 
      visibility:hide!important; 
      } 
</style>
I use this ,it can work well
