### ISSUE TITLE
How to enable Cesium's requestRenderMode via OLCesium

### ISSUE THREAD

**Issue by zsoooc** [openlayers/ol-cesium#886]
I have a map I am displaying in 2D/3D modes using Ol-Cesium 2.11 and Cesium 1.77.
Whereas the map works fine, I am now trying to enable Cesium's Request Render Mode:

```
// Create the 3D map passing the previously created ol.Map
var map3d = new olcs.OLCesium({map: olMap});
// Trying to enable Cesium's requestRenderMode - This does nothing; the map still renders continuously
var scene = map3d.getCesiumScene();
scene.requestRenderMode = true;
scene.maximumRenderTimeChange = Infinity;
```

However, it's not making any difference in CPU usage.
Any advice? Or may this be a limitation in Ol-Cesium?

**Comment by gberaudo** [comment]
Hi @zsoooc, you should call `map3d.enableAutoRenderLoop()`.
