### ISSUE TITLE
Is it possible to upload gltf/glb model with ol-cesium?

### ISSUE THREAD

**Issue by simayguzel** [openlayers/ol-cesium#946]
Hi everyone, I am trying to upload a gltf model(a sample gltf model of Cesium) using ol cesium. The Cesium version is 1.77. The problem is that the gltf model isn’t seen even though the model can be debugged on the browser console. Does the ol cesium give the possibility of adding a gltf/glb model? 

Thank you in advance!

Here is my code:
```
const ol3d = new olcs.OLCesium({map: map}); 
ol3d.setEnabled(true);
window.ol3d = ol3d; 
this.ol3d=ol3d;

var scene = this.ol3d.getCesiumScene();
var modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(Cesium.Cartesian3.fromDegrees(43.167104, 11.44543, 233.334379));

var model = scene.primitives.add(Cesium.Model.fromGltf({
    	url:"/GroundVehicle.glb",
    	color:"color('#9932CC')",
        debugShowBoundingVolume:true,
	show:true,
 	modelMatrix:modelMatrix

}));
```

**Comment by gberaudo** [comment]
Hi @simayguzel, ol-cesium converts the content of OpenLayers layers to Cesium.
There is indeed some basic support for converting points to Gltf models (which you need to provide).
See https://github.com/openlayers/ol-cesium/blob/master/src/olcs/FeatureConverter.js#L809-L823
You should create a function returning the options and put it in a `olcs_model` property. of the feature or its geometry.
