### ISSUE TITLE
Why doesn't ol-cesium import Cesium?

### ISSUE THREAD

**Issue by ruckc** [openlayers/ol-cesium#953]
I'm trying to use ol-cesium inside a react app, built with create-react-app.  When using ol-cesium, i get the `Cesium is not defined` error.  I see the references to loading Cesium onto the window object, and i've tried importing Cesium in the root index.html, with no luck.

I'm trying to load it with: 
```html
<script type="text/javascript" src="node_modules/cesium/Build/Cesium/Cesium.js"></script>
``` 

I see the network tab load the .js, but its not globally available on the window object.  So why doesn't ol-cesium just `import Cesium from `cesium/Cesium'`.  It seems like that would be a fairly standard way of loading the library (in addition to having a cesium dependency defined in package.json).

**Comment by b4l8ter** [comment]
I'm experiencing the exact same Cesium import issue building a vue.js app. Like you I have reverted to an 'old-fashioned' include via script tag and src attribute. Unlike you, this method works fine for me. Your problem is likely the relative path for src is NOT accessible at run time. I put my Cesium.js in a subfolder of public and referenced as `<script src="./libs/Cesium/Cesium.js"></script>`

**Comment by gberaudo** [comment]
It is mainly for historical reasons: CesiumJS was not available as ES6 modules at the start of the ol-cesium project.
In addition:
- it works the same for people using ol-cesium the ES6 way or the "old-fashioned" way;
- it makes lazy loading Cesium easy/performant (which is an important use case of this library).

That being said it may be time to drop the "old-fashioned"  way of using ol-cesium and as a consequence the loading of CesiumJS this way. So I will keep this issue open.

**Comment by b4l8ter** [comment]
> * it works the same for people using ol-cesium the ES6 way or the "old-fashioned" way;

We can't get it to work the ES6 way.

**Comment by ruckc** [comment]
@gberaudo - could we do conditional importing?  if its not already defined import it and make the dependency optional?  or just rev the major version to drop backwards compatibility?

**Comment by gberaudo** [comment]
@b4l8ter, how did you do? Did you check how the examples works?
- ol-cesium examples are using ES6 imports of ol-cesium (with separate "old-fashioned" Cesium);
- ol-cesium example oldfashioned.html is using both ol-cesium and cesium as external "old-fashioned" libraries.

**Comment by gberaudo** [comment]
@ruckc, ES6 does not allow conditionnal imports, unless you use the asynchronous `import()` function, but using that would be certainly painful to work with and result in bundlers generating non-optimal code.
My idea is more to drop completly the support for 'old-fashioned' builds, in a non-backward compatible update. But this all depends whether this feature is used or not and also the impact on current code: will it still be easy to lazy load the CesiumJS part on demand, like it is currently done in https://github.com/openlayers/ol-cesium/blob/master/examples/lazy.html

**Comment by b4l8ter** [comment]
> @b4l8ter, how did you do? Did you check how the examples works?
> 
> * ol-cesium examples are using ES6 imports of ol-cesium (with separate "old-fashioned" Cesium);
> * ol-cesium example oldfashioned.html is using both ol-cesium and cesium as external "old-fashioned" libraries.

Sorry but I'm not sure I understand the difference in the two methods you mention. I'm using ES6 import of ol-cesium and (old fashion) direct load of Cesium.js using script/src in my hrml.  This is the only way I can make it work at the moment. As far as I can tell, all the examples seem to use this same old-fashion method. The inject_ol_cesium.js is basically doing the same thing (referencing either dev or minified Cesium build). Also confused why this file is not named "'inject_cesium.js"' as it injects Cesium not ol-cesium?

**Comment by gberaudo** [comment]
@b4l8ter,
Your use of ol-cesium is the standard one.
Some people use ol-cesium, ol and CesiumJS as "old-fashioned" libs (no ES6 modules at all).

This is historical, "inject_ol_cesium.js" used to load OL, hence its name.

**Comment by gberaudo** [comment]
@mholthausen, you should add the Cesium external dependency. See #979.

**Comment by MM12300** [comment]
First I would like to thanks all the contributors to this project, its obviously an insane workload.
Second, I would like to agree on keeping this issue open because it's quite surprising to have this error while only copying 3 lines of the get-started. 

Why don't you add a reference to this issue or just a line like "cesium is not linked to cesium-ol so pleaase link the cesium lib locally or with a cdn in order to have this example work" ?
I don't remember if the npm page can be edited.

**Comment by gberaudo** [comment]
Hi @MM12300, I added some notes about it in the README.

**Comment by MM12300** [comment]
Thanks ! :)
