### ISSUE TITLE
(Docs) "For synchronization of maps in projections other than EPSG:4326 and EPSG:3857, see #562 branch."

### ISSUE THREAD

**Issue by matthias-ccri** [openlayers/ol-cesium#960]
There is a line on the Readme:

> For synchronization of maps in projections other than EPSG:4326 and EPSG:3857, see [#562](https://github.com/openlayers/ol-cesium/pull/562) branch.

However, it links to a PR that has been merged. Is this readme line outdated? Just wondering.

Thanks :+1:

**Comment by gberaudo** [comment]
No there is no support for client-side raster reprojection. This PR has been unmerged becaused it caused issues for some layers.
There is the customProj example about using 2 datasets.
