### ISSUE TITLE
(Docs) "It requires OpenLayers 5.x"

### ISSUE THREAD

**Issue by matthias-ccri** [openlayers/ol-cesium#961]
The readme states "It requires OpenLayers 5.x". Is this still accurate? The current `ol` package is `6.x`.

> Since version 2.0, the code is entirely based on ES6 modules and syntax. **It requires OpenLayers 5.x.** A convenient ES6 package olcs is available on npm.

**Comment by gberaudo** [comment]
Indeed. I updated the README.
