### ISSUE TITLE
pinch zoom in 3D does not work on mobile devices

### ISSUE THREAD

**Issue by lukey78** [openlayers/ol-cesium#981]
Apparently, the pinch zoom gesture does not work with OLCesium on mobile devices. 

You can check by opening an example, e.g. https://openlayers.org/ol-cesium/examples/kml.html, and then try to zoom with the zoom gesture.

Pinch zoom always zooms the whole web page, but not the 3D content. 

In "plain Cesium" this gesture works.
Is there a way to repair this behaviour?

Thanks.

**Comment by gberaudo** [comment]
Hello @lukey78 thanks for the report. I tested this example on my smartphone, both in Firefox and chrome, and it works perfectly well. On which device/browser do you encounter this issue?

**Comment by lukey78** [comment]
I tried this with an iPhone in Chrome and Safari, and also with an iPad in both browsers. Maybe it's a Apple only issue?

Please see the attached video: I opened the example, moved and pinched in the 2d map (working perfectly), then I switched to 3D mode and did the same -> pinch zooming zooms the whole web page but not the 3d content.

https://user-images.githubusercontent.com/2877837/132748284-15372b55-1563-431f-9465-c5517feba86a.mov

**Comment by gberaudo** [comment]
Hi @lukey78, it may be related to this: https://stackoverflow.com/questions/37808180/disable-viewport-zooming-ios-10-safari.
In the examples we have no headers preventing zoom. I don't have an Apple device to test. Could you continue investigating this?

**Comment by lukey78** [comment]
Hi @gberaudo - this MAY be related, but it doesn't explain why pinch zooming works in the 2D map but not in the 3D map. The example site uses the same headers. If it'd be a viewport issue then it should affect the 2D map, too. 

Does Ol-Cesium change the touch event listeners somehow?

**Comment by gberaudo** [comment]
> Does Ol-Cesium change the touch event listeners somehow?

@lukey78, no special action on these events:
- there is the `stopOpenLayersEventsPropagation` option that prevent OpenLayers to receive events, but it is not enable by default;
- we are using the default controls from Cesium so the behaviour should be the same.

**Comment by lukey78** [comment]
Strange. Do you know of any working example where someone has used ol-cesium in a mobile app and is able to zoom the 3D view on Apple devices?

**Comment by gberaudo** [comment]
@lukey78, can you try https://map.geo.admin.ch/ ? Make sure to click the 3D button as Cesium is lazy loaded.

**Comment by lukey78** [comment]
geo.admin.ch uses ol-cesium? Ok, I'll check what they do differently.

**Comment by jmgomezpoveda** [comment]
Note that geo.admin.ch seems to be using an old version of ol-cesium and OpenLayers. This used to work for me in the past, but no longer does with the recent version of ol-cesium/OpenLayers.

**Comment by jmgomezpoveda** [comment]
I have actually solved the issue with: https://stackoverflow.com/a/50823326/1816603

**Comment by jmgomezpoveda** [comment]
@gberaudo would maybe make sense to include the above code in the ol-cesium code, as part of its initialisation? Or maybe in the docs.

**Comment by gberaudo** [comment]
Thanks for the feedback @jmgomezpoveda.
I can't reproduce the issue on my mobile device. If I understand correctly this is an iOS only bug.
@pedroslvieira could you try to reproduce it? It would be good to document such workarounds in the readme.
