### ISSUE TITLE
terrainProvider not working

### ISSUE THREAD

**Issue by b4l8ter** [openlayers/ol-cesium#982]
Setting a terrain provider produces a black globe with no error message. `  ol3d.getCesiumScene().terrainProvider = new Cesium.CesiumTerrainProvider({url: myTerrainServerUrl, }); `.  Resetting the globe using `ol3d.getCesiumScene().terrainProvider = new Cesium.EllipsoidTerrainProvider({});` doesn't have any effect.  I have to revert to `ol3d = new OLCesium({ map: map });` just to get the Cesium 3D globe visible again.  My code for turning terrain on and off with pure Cesium works fine.

**Comment by gberaudo** [comment]
Hello @b4l8ter, OL-Cesium does nothing fancy with the terrain. I suggest you try using your terrain with one of the working examples in the project. If you find something there please reopen the issue.
