### ISSUE TITLE
Cannot run "make dist" on Windows

### ISSUE THREAD

**Issue by bclay1297** [openlayers/ol-cesium#984]
Downloaded the ol-cesium 2.13 from github tried to build according to instructions and the build failed see below
running on Windows 10
GNU Make version 3.78.1

N:\SupportLibraries3\ol-cesium-2.13>make dist

find: examples/data/: No such file or directory
npm install
process_begin: CreateProcess((null), npm install, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [.build/node_modules.timestamp] Error 2

Bruce

**Comment by gberaudo** [comment]
Thanks for the report @bclay1297.

If your goal is to create a new dist/olcesium.js file, you can run the following commands:
```bash
npm i
npm run build-library-debug
npm run build-library
npm run build-umd
```
