### ISSUE TITLE
Cannot work when set projection EPSG:4326

### ISSUE THREAD

**Issue by JungleHH** [openlayers/ol-cesium#986]
Hi:
When i add layer and set projection as EPSG:3857, it works well. When i use projection EPSG:4326, 2d view seems good,  but the tiles on the 3d globe are wired :(

![29781638589560_ pic_hd](https://user-images.githubusercontent.com/24989159/144696152-79232bde-be2e-4113-a651-14dcb6ff5669.jpg)
And then, i found the superficial reason from request params: it requested wrong tile number.
I will give you an example for **one tile** request params,
1) disable 3d: 
_TileMatrix=8,
TileCol:=214,
TileRow: 43_
2) enable 3d
_TileMatrix: 8
TileCol: 106
TileRow: 43
TileMatrix: 9
TileCol: 214
TileRow: 84_
It looks like that the TileMatrix may have 1 displacement distance on the numerical,  there are some correspondences between TileCol and TileRow number, i don't know.
In my opinion, the projections that ol-cesium surpport inherit from cesium.  right? So, there must be something wrong.

**Comment by gberaudo** [comment]
Hi @JungleHH, thanks for the report. Cesium supports EPSG:3857 and EPSG:4326. So it should work.
We have an example of EPSG:4326 layer but the map itself is EPSG:3857 https://openlayers.org/ol-cesium/examples/image-static.html. It would be interesting to have an example fully in EPSG:4326. This is your case, right?

**Comment by b4l8ter** [comment]
I am also experiencing the same issue with EPSG:4326 projection on the 3D globe. I think this is the same  problem reported  in Issue #798 ("_**WMS Layer doesn't work well in ol-cesisum 3d when set projection ESPG:4326**_").

**Comment by gberaudo** [comment]
Hi @JungleHH , @b4l8ter, here is how the coordinates are mapped: https://github.com/openlayers/ol-cesium/blob/master/src/olcs/core/OLImageryProvider.js#L126-L130. Maybe there is something wrong there.

**Comment by puzonevan** [comment]
@JungleHH @gberaudo I am encountering the same issue as well. 

Here's what I've tried and seems to work.

On https://github.com/openlayers/ol-cesium/blob/master/src/olcs/core/OLImageryProvider.js#L126-L130 . I set the options of GeographicTilingScheme to the default options. **new GeographicTilingScheme()** 

And then on https://github.com/openlayers/ol-cesium/blob/master/src/olcs/core/OLImageryProvider.js#L167. I simply set the const z_ = this.shouldRequestNextLevel ? level + 1 : level to just **const z_ = level**

Those two changes I was able to get a proper 4326 map to render. For reference I am using MapTiler's 4326 map from the following source https://api.maptiler.com/maps/basic-4326/{z}/{x}/{y}.png (need an API key)

What do you think would be repercussion of those following changes be for other layers using the **OLImageryProvider**??

![image](https://github.com/openlayers/ol-cesium/assets/49704737/de5bb807-e338-42ec-a504-7b68a0b9873e)

**Comment by RunBoo** [comment]
@puzonevan I tried the method you mentioned, but it didn't work. I'm not sure if it's a version issue. What version of OLCS did you use?
