### ISSUE TITLE
OL-Cesium 3d   VectorLayer to Cesium extrudedHeight

### ISSUE THREAD

**Issue by SergioAzCa** [openlayers/ol-cesium#987]
good afternoon,
I am trying to transform a layer from OL to Cesium automatically using: FeatureConverter and olVectorLayerToCesium

I have the problem in a polygonal layer in which I have added an internal property like this to each feature :
this.layerHexgrid.getSource().getFeatures().forEach((feature:any) => {
            feature.setProperties({"extrude":feature.getProperties().features.length*100})
            feature.getGeometry()['height'] = 700000;
            featuresHexExtrude.push(feature)
});
The feature have the property : 
![image](https://user-images.githubusercontent.com/33065370/155536686-1f430fcf-679e-49d1-90a8-6b7c2fbb765a.png)

As a test and then I have modified the code of FeatureConverter the part of the olPolygonGeometryToCesium
with the following :

if ((feature.getProperties().extrude )) {
      featureHeight = feature.getProperties().extrude
    }

And in the FillGeometry creation part:

fillGeometry = new Cesium.PolygonGeometry({
        // always update Cesium externs before adding a property
        extrudedHeight:featureHeight ,
        polygonHierarchy,
        perPositionHeight: false
      });

But it doesn't do anything...
![image](https://user-images.githubusercontent.com/33065370/155536511-3c6c5229-d3df-447a-979f-60e132c1504f.png)
Is totaly flat....

any ideas?

**Comment by SergioAzCa** [comment]
@gberaudo any help please?

**Comment by SergioAzCa** [comment]
@tonio @tschaub @dodecaphonic @klokan  any help?

**Comment by gberaudo** [comment]
Hi @SergioAzCa, there is no native extrusion support in OL-Cesium yet. There were some discussions https://github.com/openlayers/ol-cesium/issues/167 about it some time ago.
