### ISSUE TITLE
Vector layers not displayed

### ISSUE THREAD

**Issue by cns-solutions-admin** [openlayers/ol-cesium#992]
Should this integration with cesium still work with the current openlayers 6.14.1?

For me only image tile layers (Bing, WMS) work, whereas vector and (mapbox) vector tile layers
* are not displayed, and/or
* freeze the interface
* or sometimes only some polygons are displayed, but the interface is frozen - although the pan/zoom actions done will have changed the map view, when the vector layer is switched off

I'm using the cesium version referenced in olcs: 1.81.0

**Comment by gberaudo** [comment]
Hi @cns-solutions-admin, I can not reproduce your issue.

I updated OL version to 6.14.1 then ran:
```bash
npm i
make serve
open http://localhost:3000/examples/mvt.html
open http://localhost:3000/examples/vectors.html
```

The 2 examples worked like expected.
