### ISSUE TITLE
Can I draw graticule line on 3d globe use ol-cesium?

### ISSUE THREAD

**Issue by kevanTai** [openlayers/ol-cesium#999]
as title, like the sample -->  [cesium graticule](https://sandcastle.cesium.com/#c=xRrtcts28lUY/Wips0zJTtPpSHLuco5SZ0aOPY4uvrsq04FJSMIYInUgZNlN/E59hj5Zd/FBAiRlyXeZOWcmJoD9xH5gsfAdEcEdoxsqgpMgpZvglOZsvYw+qblw2orV+DRLJWEpFdNWezBNpymnMliyNAesX6ZpAD8G8ZzIRSSzK5IwkuZhL+q9aneehjjaBXC8C2AHi6Oo9zTA8S6AV7sAjkDR9jT9PNBbw0kur+hM0HwBO9Qzs3lMUwpjveGRGpqlmCypIOWaHhfUbijPfQONce4045zGkmVpiGZRBKOVYEsm2R3NI5IkoUZuG1KrjD9wMGSF2qWZ3odgQcLSpJyzVZ6xBGhqjDnPbmhUzFsd10LQVI7uJfwPsHNqvtHZQu1Xs3Wq2AfrVUIkVVpeZjnDuTxsB1+0ERQ5wFRum8eC0vRUDS2sIoeQBZSj7SkRMpsLslqwOJqJbIkTsETSUINb5DuIDk5TwNa7GMFgLhdmdZaJIEQQpmwMv4YIPQgODlghqSVzUxIBvUNmWRTaoEx7i3kTrYyiLh02C2CF5WMi25pgxLN0zuQ6QbfTupVTDiaIRS0GkVUEM+PAl/wBrLBzFDsSTzJnV3HeSvo4TR89UwsdKL51uVAbVoTRoFxKs43ZqLfgImEbN3TClrSwOe4DAh0ilWHwqtdrAxO5FqkBaHYuhwXd7qMWJF9ka56UQS7Fmjr8PWf3vAGRUQGVQchNHmpm0YbmEkT2ENWkzTz2J29AzrO1XNSw1WwVnTagU9LAGyeryGkDcpqJBt5qturlS4yUqNc7qnjtBsy0DL77DnQzH9R+pPjRrm33jIDLlh5lCb3w4QDfi9yKH1QzklbIGllljWxjhtlsVtgf8osGxQnfmcsla/NEkM3PgiXbUZCyhS6yayToMrujbzgv3U6r4i/4tKrMLFm1N3Zuh3c/WwS91O2qRAdVwSW7p9yce+4KubcrcsHy6NeYpHck/8h+owURhEsgfyG243rJOJ1Xplia0PuSAagCVCmkBSIwkCCZ4jAmPF5DAqMJkOZr6mTuCilH3nJuqIoc4zzoTUq2YVB1fTcK20E3OKqROjjQE14qMJoij18U1Gffo/8XOWHDSjlNfDuZ5llSqs1vlLLYf5Gt0yRgcF4Q5Ygca4a8MEO2XK3RCHPwTWAFYGCO0uRAWzEpmXpZcRj0/DT0V52EYsq4B9hVwrZ94L4GnvEsE03Q7eAv6mPgy4OmqcujE+0+AmnIrjLyHhJ54FokIl2RyP2WLVLG3UciBbi3QC70Fnmat0gHxT4Caci9jeaBO1YrnFDBJeh0S3JLg3wtaLBB77uDEhCDKS3LDUi7gWSc5hrbeqBmC8qFZuYwODacOsGhWrx8b7OhtYlBYmloZg4cpCqOcS2fEZEFIyJLRqDsscvMQTTMYKaBmcVzylgg65zFAFuOoGJLIUkKJh+A/JYLjpfozY3EFoG5x0cVixOwhU4aWkTHmlbuQ7PaNl6mhC4dzUmB3CYgtDcKjwlP7bQeHZxon3CzFkiJh2EA9yiGKvjl+ArEwbvrZycDalakFHuA2hhWdgSsnO3yOKqzE9VcraGa3VLIoy4dpNR2a6PH8nNPClomj4g6O+lce6Rvxbd0DnekHFGrJZnUhoqzFIJEvh39PMnenn8MNSFAfQdHdhJi3r4UNGY5Xq50ANauMBmHHTzxN0STPzkJpq3eH7+Ppq3g61d38ugnPe1j6XxhlUe60b9G4/HFdR2s74Ndn72fjCrVpWL3omR3PW3VDVcUPXjH/VLnU/h6f8uF540Q5MG59ahxiOasFtH4s2GJXPSDo4alJZQrghHedy+D52ZSXQQnDysaTltK42mrEzSIq8pbtV5beqyk2kfXkFqAW305Kpy1COmOsl1Hl98NHvzoJQnpJgZ77dSZocQ0ebaeIlTy1attk/XLFFEc1/tGrTrHmhLEigjCOaSzfTPE7mT0/84QWpw6EZsh1G5tyRBEPiNDELk1QyDrjroVb8kTldTwAVJDY8jvivAnI/cbRu2WiP0m0doQqW6UehHqRKcbUsraNjzdba/1W+rhbdFU66hTGGja2iygoneyZZFNXbO1rYdMW6P/rIlELQfb4Ece/KVgSxqc2yN6C5o9IxzEN6lkyyqa1xXcr5HW3Dt0+zw7GnNltDqyP7cF95z2m+7i/rfNt6KdXLYjK1FjaTturpzDzYKp7IMNoBxfwiWu5S4xzpWf97UTOUtwvTEd5qbVXD5w2vea2x9xKnr3fjx24FbYQLiYzXIq+1WTKHWP9eZDKulB4vjB+DQMD3+Ecc8NavpALaUqlZfRv0dXFw7sIhPsN3wE4ReCzVna13SrNxxD56wCHZ2OPkxGV9Ubzjbo8ejdxOGNWZfF+3H+5MFGf7+YTC7Ot/CtwE4uLl2DwAIY5Cgyt7hHrwOkm8zgQ+p3rQtVOQvgbPEyCE7g/TDqHdmGXPBy0LBeLh/Xl8tF2000w15NnuYo9x4TVCuqeMDQwz3SivG5ct/UcaqaIaEmEsWcAfI1nh6qfOnsBj6jbL7Q9yHTj3Eu3rFlG5zoV6JoxeLbkc0DzhMG4rBZ+KLAaLvIjaq8VPnRFgO9Dvxr+7tbUKhb3e8m2u3VMpvnLbu95nWrXN++/Wo9EykVzmujOjSbtG+2T6+DoV8mS9cIzyBjjKQqgedSrPTRt4lpWCyUB9Ra95ZaOf1N+Pp6PVsE/fm59ixWtCuLLuUPA9tn9Opi9WCiTWw6jOrkh7igMzgzkloRbXzRaHJFY0nSOZwW52/++eunN+N/jBpvJk9h2rLAqwtD94XMPWfLUlGftD6WUcWJXT9QGippXUK4IUNu8oyvpfdaA4B+VyfRgWph9OXJYrb9hibM5B8yOREghmqInwQFKFy0DCm8Xf3Yq2P6LBrIudxyCiomiBM2geprHc5qbu3iEuE0rTDrJkzo12hVreApjlsQvAafgu9pC+8MWIl8xNqwH3hrI7N27ZWHpoC0+3YAAH/87tWdVt+vXws1dOsA362KGvTgpNgYpPG9R+JpPLt6EADW9wbNLhYaF/tgHBYBrCOpEvDMeQ9Z+S8mq7HasWJ4RknC9AOKImv/xoBn8W2UpRPIF1gFju4gd49ZDimcitB6q39OfoEKTMaQJGyZ6Hp/J1gYTo9YvrpJHnHxOt2EZjKNV6HKbbAN1TBX2jZDVwpttM5C2QX2DyyMjNQINxDHQEqP4QPGVh+NoQf1Gz2aYlHpoRiT8KJnXi5od87S6kJpJsN2UE165p3cudjhd6vTGqr6+bWF/xtbrjIhg7XgYRR1JV2u8A0s796s41sqozjPLZFh10UdJuwuYMlJw9/9BDEneQ4rszXn+GY3bb0edgG+hsozJf0F5DhOHhBscfR6rCejKBp2YdiMKbOM3xBRofwn) ,  or have any Bro can tell me any used ol-cesium sample to reference

Thanks a lot!  : )

**Comment by gberaudo** [comment]
The Cesium scene can be retrieved with https://openlayers.org/ol-cesium/apidoc/classes/default.html#getcesiumscene.

**Comment by kevanTai** [comment]
Hi gberaudo,

Used olcesium to draw graticule on 3d globe and perfect run it now,Thanks for your help!

Kevan
